
"""This file contains PMD Release and Rule information.
"""

PMD_RELEASES = {'0.1': '2002-06-25',
                '0.2': '2002-06-27',
                '0.3': '2002-07-03',
                '0.4': '2002-07-10',
                '0.5': '2002-07-15',
                '0.6': '2002-07-18',
                '0.7': '2002-07-25',
                '0.8': '2002-07-30',
                '0.9': '2002-08-16',
                '1.0': '2002-11-04',
                '1.01': '2002-11-07',
                '1.02': '2003-01-22',
                '1.03': '2003-02-11',
                '1.04': '2003-03-21',
                '1.05': '2003-04-17',
                '1.1': '2003-06-19',
                '1.2': '2003-07-30',
                '1.2.2': '2003-10-06',
                '1.3': '2003-10-23',
                '1.4': '2004-01-07',
                '1.5': '2004-02-02',
                '1.6': '2004-03-15',
                '1.7': '2004-04-22',
                '1.8': '2004-05-19',
                '1.9': '2004-07-14',
                '2.0': '2004-10-19',
                '2.1': '2004-12-15',
                '2.2': '2005-01-31',
                '2.3': '2005-02-02',
                '3.0': '2005-03-23',
                '3.1': '2005-05-10',
                '3.2': '2005-06-21',
                '3.3': '2005-09-15',
                '3.4': '2005-11-30',
                '3.5': '2006-01-25',
                '3.6': '2006-03-29',
                '3.7': '2006-06-01',
                '3.8': '2006-10-04',
                '3.9': '2006-12-19',
                '4.0': '2007-07-20',
                '4.1': '2007-11-17',
                '4.2': '2008-03-25',
                '4.2.1': '2008-04-11',
                '4.2.2': '2008-05-20',
                '4.2.3': '2008-08-31',
                '4.2.4': '2008-10-12',
                '4.2.5': '2009-02-08',
                '4.2.6': '2011-09-14',
                '4.3': '2011-11-04',
                '5.0.0': '2012-05-01',
                '5.0.1': '2012-11-28',
                '5.0.2': '2013-02-03',
                '5.0.3': '2013-04-05',
                '5.0.4': '2013-05-01',
                '5.0.5': '2013-08-11',
                '5.1.0': '2014-02-11',
                '5.1.1': '2014-04-27',
                '5.1.2': '2014-07-20',
                '5.1.3': '2014-08-31',
                '5.2.0': '2014-10-17',
                '5.2.1': '2014-11-03',
                '5.2.2': '2014-12-03',
                '5.2.3': '2014-12-21',
                '5.3.0': '2015-04-01',
                '5.3.1': '2015-04-20',
                '5.3.2': '2015-05-22',
                '5.3.3': '2015-07-25',
                '5.3.4': '2015-09-18',
                '5.3.5': '2015-10-04',
                '5.3.6': '2015-12-04',
                '5.3.7': '2016-04-30',
                '5.3.8': '2016-11-04',
                '5.4.0': '2015-10-04',
                '5.4.1': '2015-12-04',
                '5.4.2': '2016-05-29',
                '5.4.3': '2016-11-04',
                '5.4.4': '2017-01-28',
                '5.4.5': '2017-02-25',
                '5.4.6': '2017-03-27',
                '5.5.0': '2016-07-25'}

# all deprecated rulesets, source: https://pmd.github.io/pmd-6.12.0/pmd_rules_java.html#additional-rulesets
PMD_OLD_RULESETS = {'android': 'CallSuperFirst, CallSuperLast, DoNotHardCodeSDCard',
                    'basic': 'AvoidBranchingStatementAsLastInLoop, AvoidDecimalLiteralsInBigDecimalConstructor, AvoidMultipleUnaryOperators, AvoidThreadGroup, AvoidUsingHardCodedIP, AvoidUsingOctalValues, BigIntegerInstantiation, BooleanInstantiation, BrokenNullCheck, CheckResultSet, CheckSkipResult, ClassCastExceptionWithToArray, CollapsibleIfStatements, DontCallThreadRun, DontUseFloatTypeForLoopIndices, DoubleCheckedLocking, ExtendsObject, ForLoopShouldBeWhileLoop, JumbledIncrementer, MisplacedNullCheck, OverrideBothEqualsAndHashcode, ReturnFromFinallyBlock, SimplifiedTernary, UnconditionalIfStatement',
                    'braces': 'ForLoopsMustUseBraces, IfElseStmtsMustUseBraces, IfStmtsMustUseBraces, WhileLoopsMustUseBraces',
                    'clone': 'CloneMethodMustBePublic, CloneMethodMustImplementCloneable, CloneMethodReturnTypeMustMatchClassName, CloneThrowsCloneNotSupportedException, ProperCloneImplementation',
                    'codesize': 'CyclomaticComplexity, ExcessiveClassLength, ExcessiveMethodLength, ExcessiveParameterList, ExcessivePublicCount, ModifiedCyclomaticComplexity, NcssConstructorCount, NcssCount, NcssMethodCount, NcssTypeCount, NPathComplexity, StdCyclomaticComplexity, TooManyFields, TooManyMethods',
                    'comments': 'CommentContent, CommentDefaultAccessModifier, CommentRequired, CommentSize',
                    'controversial': 'AssignmentInOperand, AtLeastOneConstructor, AvoidAccessibilityAlteration, AvoidFinalLocalVariable, AvoidLiteralsInIfCondition, AvoidPrefixingMethodParameters, AvoidUsingNativeCode, AvoidUsingShortType, AvoidUsingVolatile, CallSuperInConstructor, DataflowAnomalyAnalysis, DefaultPackage, DoNotCallGarbageCollectionExplicitly, DontImportSun, NullAssignment, OneDeclarationPerLine, OnlyOneReturn, SuspiciousOctalEscape, UnnecessaryConstructor, UnnecessaryParentheses, UseConcurrentHashMap, UseObjectForClearerAPI',
                    'coupling': 'CouplingBetweenObjects, ExcessiveImports, LawOfDemeter, LooseCoupling, LoosePackageCoupling',
                    'design': 'AbstractClassWithoutAbstractMethod, AbstractClassWithoutAnyMethod, AccessorClassGeneration, AccessorMethodGeneration, AssignmentToNonFinalStatic, AvoidDeeplyNestedIfStmts, AvoidInstanceofChecksInCatchClause, AvoidProtectedFieldInFinalClass, AvoidProtectedMethodInFinalClassNotExtending, AvoidReassigningParameters, AvoidSynchronizedAtMethodLevel, BadComparison, ClassWithOnlyPrivateConstructorsShouldBeFinal, CloseResource, CompareObjectsWithEquals, ConfusingTernary, ConstantsInInterface, ConstructorCallsOverridableMethod, DataClass, DefaultLabelNotLastInSwitchStmt, EmptyMethodInAbstractClassShouldBeAbstract, EqualsNull, FieldDeclarationsShouldBeAtStartOfClass, FinalFieldCouldBeStatic, GodClass, IdempotentOperations, ImmutableField, InstantiationToGetClass, LogicInversion, MissingBreakInSwitch, MissingStaticMethodInNonInstantiatableClass, NonCaseLabelInSwitchStatement, NonStaticInitializer, NonThreadSafeSingleton, OptimizableToArrayCall, PositionLiteralsFirstInCaseInsensitiveComparisons, PositionLiteralsFirstInComparisons, PreserveStackTrace, ReturnEmptyArrayRatherThanNull, SimpleDateFormatNeedsLocale, SimplifyBooleanExpressions, SimplifyBooleanReturns, SimplifyConditional, SingleMethodSingleton, SingletonClassReturningNewInstance, SingularField, SwitchDensity, SwitchStmtsShouldHaveDefault, TooFewBranchesForASwitchStatement, UncommentedEmptyConstructor, UncommentedEmptyMethodBody, UnnecessaryLocalBeforeReturn, UnsynchronizedStaticDateFormatter, UseCollectionIsEmpty, UseLocaleWithCaseConversions, UseNotifyAllInsteadOfNotify, UseUtilityClass, UseVarargs',
                    'empty': 'EmptyCatchBlock, EmptyFinallyBlock, EmptyIfStmt, EmptyInitializer, EmptyStatementBlock, EmptyStatementNotInLoop, EmptyStaticInitializer, EmptySwitchStatements, EmptySynchronizedBlock, EmptyTryBlock, EmptyWhileStmt',
                    'finalizers': 'AvoidCallingFinalize, EmptyFinalizer, FinalizeDoesNotCallSuperFinalize, FinalizeOnlyCallsSuperFinalize, FinalizeOverloaded, FinalizeShouldBeProtected',
                    'imports': 'DontImportJavaLang, DuplicateImports, ImportFromSamePackage, TooManyStaticImports, UnnecessaryFullyQualifiedName, UnusedImports',
                    'j2ee': 'DoNotCallSystemExit, DoNotUseThreads, LocalHomeNamingConvention, LocalInterfaceSessionNamingConvention, MDBAndSessionBeanNamingConvention, RemoteInterfaceNamingConvention, RemoteSessionInterfaceNamingConvention, StaticEJBFieldShouldBeFinal, UseProperClassLoader',
                    'javabeans': 'BeanMembersShouldSerialize, MissingSerialVersionUID',
                    'junit': 'JUnitAssertionsShouldIncludeMessage, JUnitSpelling, JUnitStaticSuite, JUnitTestContainsTooManyAsserts, JUnitTestsShouldIncludeAssert, SimplifyBooleanAssertion, TestClassWithoutTestCases, UnnecessaryBooleanAssertion, UseAssertEqualsInsteadOfAssertTrue, UseAssertNullInsteadOfAssertTrue, UseAssertSameInsteadOfAssertTrue, UseAssertTrueInsteadOfAssertEquals',
                    'metrics': 'CyclomaticComplexity',
                    'migrating_to_junit4': 'JUnit4SuitesShouldUseSuiteAnnotation, JUnit4TestShouldUseAfterAnnotation, JUnit4TestShouldUseBeforeAnnotation, JUnit4TestShouldUseTestAnnotation, JUnitUseExpected',
                    'migrating': 'AvoidAssertAsIdentifier, AvoidEnumAsIdentifier, ByteInstantiation, ForLoopCanBeForeach, IntegerInstantiation, JUnit4SuitesShouldUseSuiteAnnotation, JUnit4TestShouldUseAfterAnnotation, JUnit4TestShouldUseBeforeAnnotation, JUnit4TestShouldUseTestAnnotation, JUnitUseExpected, LongInstantiation, ReplaceEnumerationWithIterator, ReplaceHashtableWithMap, ReplaceVectorWithList, ShortInstantiation',
                    'migrating_to_13': 'ReplaceEnumerationWithIterator, ReplaceHashtableWithMap, ReplaceVectorWithList',
                    'migrating_to_14': 'AvoidAssertAsIdentifier',
                    'migrating_to_15': 'AvoidEnumAsIdentifier, ByteInstantiation, IntegerInstantiation, LongInstantiation, ShortInstantiation',
                    'naming': 'AbstractNaming, AvoidDollarSigns, AvoidFieldNameMatchingMethodName, AvoidFieldNameMatchingTypeName, BooleanGetMethodName, ClassNamingConventions, GenericsNaming, LongVariable, MethodNamingConventions, MethodWithSameNameAsEnclosingClass, MisleadingVariableName, MIsLeadingVariableName, NoPackage, PackageCase, ShortClassName, ShortMethodName, ShortVariable, SuspiciousConstantFieldName, SuspiciousEqualsMethodName, SuspiciousHashcodeMethodName, VariableNamingConventions',
                    'optimizations': 'AddEmptyString, AvoidArrayLoops, AvoidInstantiatingObjectsInLoops, LocalVariableCouldBeFinal, MethodArgumentCouldBeFinal, PrematureDeclaration, RedundantFieldInitializer, SimplifyStartsWith, UnnecessaryWrapperObjectCreation, UseArrayListInsteadOfVector, UseArraysAsList, UseStringBufferForStringAppends',
                    'quickstart': 'AbstractClassWithoutAnyMethod, AssignmentInOperand, AssignmentToNonFinalStatic, AvoidAccessibilityAlteration, AvoidBranchingStatementAsLastInLoop, AvoidCatchingThrowable, AvoidDecimalLiteralsInBigDecimalConstructor, AvoidDollarSigns, AvoidInstanceofChecksInCatchClause, AvoidMultipleUnaryOperators, AvoidProtectedFieldInFinalClass, AvoidProtectedMethodInFinalClassNotExtending, AvoidStringBufferField, AvoidThreadGroup, AvoidUsingHardCodedIP, AvoidUsingOctalValues, AvoidUsingVolatile, BadComparison, BigIntegerInstantiation, BooleanInstantiation, BrokenNullCheck, CheckResultSet, CheckSkipResult, ClassCastExceptionWithToArray, ClassNamingConventions, ClassWithOnlyPrivateConstructorsShouldBeFinal, CloneMethodMustBePublic, CloneMethodMustImplementCloneable, CloneMethodReturnTypeMustMatchClassName, CloneThrowsCloneNotSupportedException, CloseResource, CompareObjectsWithEquals, ConstantsInInterface, ControlStatementBraces, DefaultLabelNotLastInSwitchStmt, DoNotCallGarbageCollectionExplicitly, DoNotExtendJavaLangError, DoNotExtendJavaLangThrowable, DontCallThreadRun, DontImportJavaLang, DontUseFloatTypeForLoopIndices, DoubleCheckedLocking, DuplicateImports, EmptyCatchBlock, EmptyFinalizer, EmptyFinallyBlock, EmptyIfStmt, EmptyInitializer, EmptyStatementBlock, EmptyStatementNotInLoop, EmptySwitchStatements, EmptySynchronizedBlock, EmptyTryBlock, EmptyWhileStmt, EqualsNull, ExtendsObject, FinalFieldCouldBeStatic, ForLoopCanBeForeach, ForLoopShouldBeWhileLoop, FormalParameterNamingConventions, GenericsNaming, GuardLogStatement, IdempotentOperations, IdenticalCatchBranches, ImportFromSamePackage, InstantiationToGetClass, JumbledIncrementer, LocalVariableNamingConventions, LogicInversion, LooseCoupling, MethodNamingConventions, MisplacedNullCheck, MissingBreakInSwitch, MissingOverride, MissingStaticMethodInNonInstantiatableClass, NonCaseLabelInSwitchStatement, NonStaticInitializer, NonThreadSafeSingleton, NoPackage, OneDeclarationPerLine, OptimizableToArrayCall, OverrideBothEqualsAndHashcode, PackageCase, PositionLiteralsFirstInCaseInsensitiveComparisons, PositionLiteralsFirstInComparisons, PreserveStackTrace, ProperCloneImplementation, ProperLogger, ReturnEmptyArrayRatherThanNull, ReturnFromFinallyBlock, SimplifiedTernary, SimplifyBooleanReturns, SimplifyConditional, SingleMethodSingleton, SingletonClassReturningNewInstance, SingularField, SuspiciousEqualsMethodName, SuspiciousHashcodeMethodName, SuspiciousOctalEscape, SwitchStmtsShouldHaveDefault, UncommentedEmptyConstructor, UncommentedEmptyMethodBody, UnconditionalIfStatement, UnnecessaryAnnotationValueElement, UnnecessaryConstructor, UnnecessaryConversionTemporary, UnnecessaryFullyQualifiedName, UnnecessaryLocalBeforeReturn, UnnecessaryModifier, UnnecessaryReturn, UnsynchronizedStaticDateFormatter, UnusedFormalParameter, UnusedImports, UnusedLocalVariable, UnusedNullCheckInEquals, UnusedPrivateField, UnusedPrivateMethod, UseAssertEqualsInsteadOfAssertTrue, UseAssertNullInsteadOfAssertTrue, UseAssertSameInsteadOfAssertTrue, UseAssertTrueInsteadOfAssertEquals, UseCollectionIsEmpty, UseEqualsToCompareStrings, UselessOperationOnImmutable, UselessOverridingMethod, UselessParentheses, UselessQualifiedThis, UseLocaleWithCaseConversions, UseNotifyAllInsteadOfNotify, UseUtilityClass',
                    'sunsecure': 'ArrayIsStoredDirectly, MethodReturnsInternalArray',
                    'strictexception': 'AvoidCatchingGenericException, AvoidCatchingNPE, AvoidCatchingThrowable, AvoidLosingExceptionInformation, AvoidRethrowingException, AvoidThrowingNewInstanceOfSameException, AvoidThrowingNullPointerException, AvoidThrowingRawExceptionTypes, DoNotExtendJavaLangError, DoNotThrowExceptionInFinally, ExceptionAsFlowControl, SignatureDeclareThrowsException',
                    'strings': 'AppendCharacterWithChar, AvoidDuplicateLiterals, AvoidStringBufferField, ConsecutiveAppendsShouldReuse, ConsecutiveLiteralAppends, InefficientEmptyStringCheck, InefficientStringBuffering, InsufficientStringBufferDeclaration, StringBufferInstantiationWithChar, StringInstantiation, StringToString, UnnecessaryCaseChange, UseEqualsToCompareStrings, UseIndexOfChar, UselessStringValueOf, UseStringBufferLength',
                    'typeresolution': 'CloneMethodMustImplementCloneable, LooseCoupling, SignatureDeclareThrowsException, UnusedImports',
                    'unnecessary': 'UnnecessaryConversionTemporary, UnnecessaryFinalModifier, UnnecessaryModifier, UnnecessaryReturn, UnusedNullCheckInEquals, UselessOperationOnImmutable, UselessOverridingMethod, UselessParentheses, UselessQualifiedThis',
                    'unusedcode': 'UnusedFormalParameter, UnusedLocalVariable, UnusedPrivateField, UnusedPrivateMethod',

                    # these are new rulesets (as of pmd 6) tha re-organize some rules
                    'bestpractices': 'AbstractClassWithoutAbstractMethod,AccessorClassGeneration,AccessorMethodGeneration,ArrayIsStoredDirectly,AvoidPrintStackTrace,AvoidReassigningLoopVariables,AvoidReassigningParameters,AvoidStringBufferField,AvoidUsingHardCodedIP,CheckResultSet,ConstantsInInterface,DefaultLabelNotLastInSwitchStmt,ForLoopCanBeForeach,ForLoopVariableCount,GuardLogStatement,JUnit4SuitesShouldUseSuiteAnnotation,JUnit4TestShouldUseAfterAnnotation,JUnit4TestShouldUseBeforeAnnotation,JUnit4TestShouldUseTestAnnotation,JUnitAssertionsShouldIncludeMessage,JUnitTestContainsTooManyAsserts,JUnitTestsShouldIncludeAssert,JUnitUseExpected,LooseCoupling,MethodReturnsInternalArray,MissingOverride,OneDeclarationPerLine,PositionLiteralsFirstInCaseInsensitiveComparisons,PositionLiteralsFirstInComparisons,PreserveStackTrace,ReplaceEnumerationWithIterator,ReplaceHashtableWithMap,ReplaceVectorWithList,SwitchStmtsShouldHaveDefault,SystemPrintln,UnusedFormalParameter,UnusedImports,UnusedLocalVariable,UnusedPrivateField,UnusedPrivateMethod,UseAssertEqualsInsteadOfAssertTrue,UseAssertNullInsteadOfAssertTrue,UseAssertSameInsteadOfAssertTrue,UseAssertTrueInsteadOfAssertEquals,UseCollectionIsEmpty,UseTryWithResources,UseVarargs',
                    'multithreading': 'AvoidSynchronizedAtMethodLevel,AvoidThreadGroup,AvoidUsingVolatile,DoNotUseThreads,DontCallThreadRun,DoubleCheckedLocking,NonThreadSafeSingleton,UnsynchronizedStaticDateFormatter,UnsynchronizedStaticFormatter,UseConcurrentHashMap,UseNotifyAllInsteadOfNotify',
                    'performance': 'AddEmptyString,AppendCharacterWithChar,AvoidArrayLoops,AvoidFileStream,AvoidInstantiatingObjectsInLoops,AvoidUsingShortType,BigIntegerInstantiation,BooleanInstantiation,ByteInstantiation,ConsecutiveAppendsShouldReuse,ConsecutiveLiteralAppends,InefficientEmptyStringCheck,InefficientStringBuffering,InsufficientStringBufferDeclaration,IntegerInstantiation,LongInstantiation,OptimizableToArrayCall,RedundantFieldInitializer,ShortInstantiation,SimplifyStartsWith,StringInstantiation,StringToString,TooFewBranchesForASwitchStatement,UnnecessaryWrapperObjectCreation,UseArrayListInsteadOfVector,UseArraysAsList,UseIndexOfChar,UselessStringValueOf,UseStringBufferForStringAppends,UseStringBufferLength',
                    'security': 'HardCodedCryptoKey,InsecureCryptoIv',
                    'errorprone': 'AssignmentInOperand,AssignmentToNonFinalStatic,AvoidAccessibilityAlteration,AvoidAssertAsIdentifier,AvoidBranchingStatementAsLastInLoop,AvoidCallingFinalize,AvoidCatchingNPE,AvoidCatchingThrowable,AvoidDecimalLiteralsInBigDecimalConstructor,AvoidDuplicateLiterals,AvoidEnumAsIdentifier,AvoidFieldNameMatchingMethodName,AvoidFieldNameMatchingTypeName,AvoidInstanceofChecksInCatchClause,AvoidLiteralsInIfCondition,AvoidLosingExceptionInformation,AvoidMultipleUnaryOperators,AvoidUsingOctalValues,BadComparison,BeanMembersShouldSerialize,BrokenNullCheck,CallSuperFirst,CallSuperLast,CheckSkipResult,ClassCastExceptionWithToArray,CloneMethodMustBePublic,CloneMethodMustImplementCloneable,CloneMethodReturnTypeMustMatchClassName,CloneThrowsCloneNotSupportedException,CloseResource,CompareObjectsWithEquals,ConstructorCallsOverridableMethod,DataflowAnomalyAnalysis,DoNotCallGarbageCollectionExplicitly,DoNotCallSystemExit,DoNotExtendJavaLangThrowable,DoNotHardCodeSDCard,DoNotThrowExceptionInFinally,DontImportSun,DontUseFloatTypeForLoopIndices,EmptyCatchBlock,EmptyFinalizer,EmptyFinallyBlock,EmptyIfStmt,EmptyInitializer,EmptyStatementBlock,EmptyStatementNotInLoop,EmptySwitchStatements,EmptySynchronizedBlock,EmptyTryBlock,EmptyWhileStmt,EqualsNull,FinalizeDoesNotCallSuperFinalize,FinalizeOnlyCallsSuperFinalize,FinalizeOverloaded,FinalizeShouldBeProtected,IdempotentOperations,ImportFromSamePackage,InstantiationToGetClass,InvalidSlf4jMessageFormat,JumbledIncrementer,JUnitSpelling,JUnitStaticSuite,LoggerIsNotStaticFinal,MethodWithSameNameAsEnclosingClass,MisplacedNullCheck,MissingBreakInSwitch,MissingSerialVersionUID,MissingStaticMethodInNonInstantiatableClass,MoreThanOneLogger,NonCaseLabelInSwitchStatement,NonStaticInitializer,NullAssignment,OverrideBothEqualsAndHashcode,ProperCloneImplementation,ProperLogger,ReturnEmptyArrayRatherThanNull,ReturnFromFinallyBlock,SimpleDateFormatNeedsLocale,SingleMethodSingleton,SingletonClassReturningNewInstance,StaticEJBFieldShouldBeFinal,StringBufferInstantiationWithChar,SuspiciousEqualsMethodName,SuspiciousHashcodeMethodName,SuspiciousOctalEscape,TestClassWithoutTestCases,UnconditionalIfStatement,UnnecessaryBooleanAssertion,UnnecessaryCaseChange,UnnecessaryConversionTemporary,UnusedNullCheckInEquals,UseCorrectExceptionLogging,UseEqualsToCompareStrings,UselessOperationOnImmutable,UseLocaleWithCaseConversions,UseProperClassLoader',
                    'documentation': 'CommentContent,CommentRequired,CommentSize,UncommentedEmptyConstructor,UncommentedEmptyMethodBody',
                    'design': 'AbstractClassWithoutAnyMethod,AvoidCatchingGenericException,AvoidDeeplyNestedIfStmts,AvoidRethrowingException,AvoidThrowingNewInstanceOfSameException,AvoidThrowingNullPointerException,AvoidThrowingRawExceptionTypes,ClassWithOnlyPrivateConstructorsShouldBeFinal,CollapsibleIfStatements,CouplingBetweenObjects,CyclomaticComplexity,DataClass,DoNotExtendJavaLangError,ExceptionAsFlowControl,ExcessiveClassLength,ExcessiveImports,ExcessiveMethodLength,ExcessiveParameterList,ExcessivePublicCount,FinalFieldCouldBeStatic,GodClass,ImmutableField,LawOfDemeter,LogicInversion,LoosePackageCoupling,ModifiedCyclomaticComplexity,NcssConstructorCount,NcssCount,NcssMethodCount,NcssTypeCount,NPathComplexity,SignatureDeclareThrowsException,SimplifiedTernary,SimplifyBooleanAssertion,SimplifyBooleanExpressions,SimplifyBooleanReturns,SimplifyConditional,SingularField,StdCyclomaticComplexity,SwitchDensity,TooManyFields,TooManyMethods,UselessOverridingMethod,UseObjectForClearerAPI,UseUtilityClass',
                    'codestyle': 'AbstractNaming,AtLeastOneConstructor,AvoidDollarSigns,AvoidFinalLocalVariable,AvoidPrefixingMethodParameters,AvoidProtectedFieldInFinalClass,AvoidProtectedMethodInFinalClassNotExtending,AvoidUsingNativeCode,BooleanGetMethodName,CallSuperInConstructor,ClassNamingConventions,CommentDefaultAccessModifier,ConfusingTernary,ControlStatementBraces,DefaultPackage,DontImportJavaLang,DuplicateImports,EmptyMethodInAbstractClassShouldBeAbstract,ExtendsObject,FieldDeclarationsShouldBeAtStartOfClass,FieldNamingConventions,ForLoopShouldBeWhileLoop,ForLoopsMustUseBraces,FormalParameterNamingConventions,GenericsNaming,IdenticalCatchBranches,IfElseStmtsMustUseBraces,IfStmtsMustUseBraces,LinguisticNaming,LocalHomeNamingConvention,LocalInterfaceSessionNamingConvention,LocalVariableCouldBeFinal,LocalVariableNamingConventions,LongVariable,MDBAndSessionBeanNamingConvention,MethodArgumentCouldBeFinal,MethodNamingConventions,MIsLeadingVariableName,NoPackage,OnlyOneReturn,PackageCase,PrematureDeclaration,RemoteInterfaceNamingConvention,RemoteSessionInterfaceNamingConvention,ShortClassName,ShortMethodName,ShortVariable,SuspiciousConstantFieldName,TooManyStaticImports,UnnecessaryAnnotationValueElement,UnnecessaryConstructor,UnnecessaryFullyQualifiedName,UnnecessaryLocalBeforeReturn,UnnecessaryModifier,UnnecessaryReturn,UseDiamondOperator,UselessParentheses,UselessQualifiedThis,UseUnderscoresInNumericLiterals,VariableNamingConventions,WhileLoopsMustUseBraces'
                    }

PMD_RULES_SINCE = {
 'PMD_AAA': {'pmd_category': 'controversial',
             'pmd_name': 'AvoidAccessibilityAlteration',
             'pmd_since': '4.1'},
 'PMD_AAL': {'pmd_category': 'optimizations',
             'pmd_name': 'AvoidArrayLoops',
             'pmd_since': '3.5'},
 'PMD_ABSALIL': {'pmd_category': 'basic',
                 'pmd_name': 'AvoidBranchingStatementAsLastInLoop',
                 'pmd_since': '5.0'},
 'PMD_ACF': {'pmd_category': 'finalizers',
             'pmd_name': 'AvoidCallingFinalize',
             'pmd_since': '3.0'},
 'PMD_ACGE': {'pmd_category': 'strictexception',
              'pmd_name': 'AvoidCatchingGenericException',
              'pmd_since': '4.2.6'},
 'PMD_ACI': {'pmd_category': 'design',
             'pmd_name': 'AvoidConstantsInterface',
             'pmd_since': '3.5'},
 'PMD_ACNPE': {'pmd_category': 'strictexception',
               'pmd_name': 'AvoidCatchingNPE',
               'pmd_since': '1.8'},
 'PMD_ACT': {'pmd_category': 'strictexception',
             'pmd_name': 'AvoidCatchingThrowable',
             'pmd_since': '1.2'},
 'PMD_ACWAM': {'pmd_category': 'design',
               'pmd_name': 'AbstractClassWithoutAbstractMethod',
               'pmd_since': '3.0'},
 'PMD_ADL': {'pmd_category': 'strings',
             'pmd_name': 'AvoidDuplicateLiterals',
             'pmd_since': '1.0'},
 'PMD_ADLIBDC': {'pmd_category': 'basic',
                 'pmd_name': 'AvoidDecimalLiteralsInBigDecimalConstructor',
                 'pmd_since': '3.4'},
 'PMD_ADS': {'pmd_category': 'naming',
             'pmd_name': 'AvoidDollarSigns',
             'pmd_since': '1.5'},
 'PMD_AES': {'pmd_category': 'optimizations',
             'pmd_name': 'AddEmptyString',
             'pmd_since': '4.0'},
 'PMD_AFNMMN': {'pmd_category': 'naming',
                'pmd_name': 'AvoidFieldNameMatchingMethodName',
                'pmd_since': '3.0'},
 'PMD_AFNMTN': {'pmd_category': 'naming',
                'pmd_name': 'AvoidFieldNameMatchingTypeName',
                'pmd_since': '3.0'},
 'PMD_AICICC': {'pmd_category': 'design',
                'pmd_name': 'AvoidInstanceofChecksInCatchClause',
                'pmd_since': '3.0'},
 'PMD_AIO': {'pmd_category': 'controversial',
             'pmd_name': 'AssignmentInOperand',
             'pmd_since': '1.03'},
 'PMD_AISD': {'pmd_category': 'sunsecure',
              'pmd_name': 'ArrayIsStoredDirectly',
              'pmd_since': '2.2'},
 'PMD_ALEI': {'pmd_category': 'strictexception',
              'pmd_name': 'AvoidLosingExceptionInformation',
              'pmd_since': '4.2.6'},
 'PMD_AMUO': {'pmd_category': 'basic',
              'pmd_name': 'AvoidMultipleUnaryOperators',
              'pmd_since': '4.2'},
 'PMD_APFIFC': {'pmd_category': 'design',
                'pmd_name': 'AvoidProtectedFieldInFinalClass',
                'pmd_since': '2.1'},
 'PMD_APMIFCNE': {'pmd_category': 'design',
                  'pmd_name': 'AvoidProtectedMethodInFinalClassNotExtending',
                  'pmd_since': '5.1'},
 'PMD_APMP': {'pmd_category': 'controversial',
              'pmd_name': 'AvoidPrefixingMethodParameters',
              'pmd_since': '5.0'},
 'PMD_APST': {'pmd_category': 'logging-java',
              'pmd_name': 'AvoidPrintStackTrace',
              'pmd_since': '3.2'},
 'PMD_ARE': {'pmd_category': 'strictexception',
             'pmd_name': 'AvoidRethrowingException',
             'pmd_since': '3.8'},
 'PMD_ARP': {'pmd_category': 'design',
             'pmd_name': 'AvoidReassigningParameters',
             'pmd_since': '1.0'},
 'PMD_ASAML': {'pmd_category': 'design',
               'pmd_name': 'AvoidSynchronizedAtMethodLevel',
               'pmd_since': '3.0'},
 'PMD_ASBF': {'pmd_category': 'strings',
              'pmd_name': 'AvoidStringBufferField',
              'pmd_since': '4.2'},
 'PMD_ATG': {'pmd_category': 'basic',
             'pmd_name': 'AvoidThreadGroup',
             'pmd_since': '3.6'},
 'PMD_ATNFS': {'pmd_category': 'design',
               'pmd_name': 'AssignmentToNonFinalStatic',
               'pmd_since': '2.2'},
 'PMD_ATNIOSE': {'pmd_category': 'strictexception',
                 'pmd_name': 'AvoidThrowingNewInstanceOfSameException',
                 'pmd_since': '4.2.5'},
 'PMD_ATNPE': {'pmd_category': 'strictexception',
               'pmd_name': 'AvoidThrowingNullPointerException',
               'pmd_since': '1.8'},
 'PMD_ATRET': {'pmd_category': 'strictexception',
               'pmd_name': 'AvoidThrowingRawExceptionTypes',
               'pmd_since': '1.8'},
 'PMD_AUHCIP': {'pmd_category': 'basic',
                'pmd_name': 'AvoidUsingHardCodedIP',
                'pmd_since': '4.1'},
 'PMD_AUNC': {'pmd_category': 'controversial',
              'pmd_name': 'AvoidUsingNativeCode',
              'pmd_since': '4.1'},
 'PMD_AUOV': {'pmd_category': 'basic',
              'pmd_name': 'AvoidUsingOctalValues',
              'pmd_since': '3.9'},
 'PMD_AbCWAM': {'pmd_category': 'design',
                'pmd_name': 'AbstractClassWithoutAnyMethod',
                'pmd_since': '4.2'},
 'PMD_BC': {'pmd_category': 'design',
            'pmd_name': 'BadComparison',
            'pmd_since': '1.8'},
 'PMD_BGMN': {'pmd_category': 'naming',
              'pmd_name': 'BooleanGetMethodName',
              'pmd_since': '4.0'},
 'PMD_BI': {'pmd_category': 'basic',
            'pmd_name': 'BooleanInstantiation',
            'pmd_since': '1.2'},
 'PMD_BII': {'pmd_category': 'basic',
             'pmd_name': 'BigIntegerInstantiation',
             'pmd_since': '3.9'},
 'PMD_BNC': {'pmd_category': 'basic',
             'pmd_name': 'BrokenNullCheck',
             'pmd_since': '3.8'},
 'PMD_CASR': {'pmd_category': 'strings',
              'pmd_name': 'ConsecutiveAppendsShouldReuse',
              'pmd_since': '5.1'},
 'PMD_CCEWTA': {'pmd_category': 'basic',
                'pmd_name': 'ClassCastExceptionWithToArray',
                'pmd_since': '3.4'},
 'PMD_CCOM': {'pmd_category': 'design',
              'pmd_name': 'ConstructorCallsOverridableMethod',
              'pmd_since': '1.04'},
 'PMD_CIS': {'pmd_category': 'basic',
             'pmd_name': 'CollapsibleIfStatements',
             'pmd_since': '3.1'},
 'PMD_CLA': {'pmd_category': 'strings',
             'pmd_name': 'ConsecutiveLiteralAppends',
             'pmd_since': '3.5'},
 'PMD_CNC': {'pmd_category': 'naming',
             'pmd_name': 'ClassNamingConventions',
             'pmd_since': '1.2'},
 'PMD_CRS': {'pmd_category': 'basic',
             'pmd_name': 'CheckResultSet',
             'pmd_since': '4.1'},
 'PMD_CSR': {'pmd_category': 'basic',
             'pmd_name': 'CheckSkipResult',
             'pmd_since': '5.0'},
 'PMD_CTCNSE': {'pmd_category': 'clone',
                'pmd_name': 'CloneThrowsCloneNotSupportedException',
                'pmd_since': '1.9'},
 'PMD_CWOPCSBF': {'pmd_category': 'design',
                  'pmd_name': 'ClassWithOnlyPrivateConstructorsShouldBeFinal',
                  'pmd_since': '4.1'},
 'PMD_ClMMIC': {'pmd_category': 'typeresolution',
                'pmd_name': 'CloneMethodMustImplementCloneable',
                'pmd_since': '3.9'},
 'PMD_ClR': {'pmd_category': 'design',
             'pmd_name': 'CloseResource',
             'pmd_since': '1.2.2'},
 'PMD_DCL': {'pmd_category': 'basic',
             'pmd_name': 'DoubleCheckedLocking',
             'pmd_since': '1.04'},
 'PMD_DCTR': {'pmd_category': 'basic',
              'pmd_name': 'DontCallThreadRun',
              'pmd_since': '4.3'},
 'PMD_DI': {'pmd_category': 'imports',
            'pmd_name': 'DuplicateImports',
            'pmd_since': '0.5'},
 'PMD_DIJL': {'pmd_category': 'imports',
              'pmd_name': 'DontImportJavaLang',
              'pmd_since': '0.5'},
 'PMD_DIS': {'pmd_category': 'controversial',
             'pmd_name': 'DontImportSun',
             'pmd_since': '1.5'},
 'PMD_DLNLISS': {'pmd_category': 'design',
                 'pmd_name': 'DefaultLabelNotLastInSwitchStmt',
                 'pmd_since': '1.5'},
 'PMD_DNCGCE': {'pmd_category': 'controversial',
                'pmd_name': 'DoNotCallGarbageCollectionExplicitly',
                'pmd_since': '4.2'},
 'PMD_DNCSE': {'pmd_category': 'j2ee',
               'pmd_name': 'DoNotCallSystemExit',
               'pmd_since': '4.1'},
 'PMD_DNEJLE': {'pmd_category': 'strictexception',
                'pmd_name': 'DoNotExtendJavaLangError',
                'pmd_since': '4.0'},
 'PMD_DNTEIF': {'pmd_category': 'strictexception',
                'pmd_name': 'DoNotThrowExceptionInFinally',
                'pmd_since': '4.2'},
 'PMD_DP': {'pmd_category': 'controversial',
            'pmd_name': 'DefaultPackage',
            'pmd_since': '3.4'},
 'PMD_DUFTFLI': {'pmd_category': 'basic',
                 'pmd_name': 'DontUseFloatTypeForLoopIndices',
                 'pmd_since': '4.3'},
 'PMD_EAFC': {'pmd_category': 'strictexception',
              'pmd_name': 'ExceptionAsFlowControl',
              'pmd_since': '1.8'},
 'PMD_ECB': {'pmd_category': 'empty',
             'pmd_name': 'EmptyCatchBlock',
             'pmd_since': '0.1'},
 'PMD_EF': {'pmd_category': 'finalizers',
            'pmd_name': 'EmptyFinalizer',
            'pmd_since': '1.5'},
 'PMD_EFB': {'pmd_category': 'empty',
             'pmd_name': 'EmptyFinallyBlock',
             'pmd_since': '0.4'},
 'PMD_EIS': {'pmd_category': 'empty',
             'pmd_name': 'EmptyIfStmt',
             'pmd_since': '0.1'},
 'PMD_EMIACSBA': {'pmd_category': 'design',
                  'pmd_name': 'EmptyMethodInAbstractClassShouldBeAbstract',
                  'pmd_since': '4.1'},
 'PMD_EN': {'pmd_category': 'design',
            'pmd_name': 'EqualsNull',
            'pmd_since': '1.9'},
 'PMD_EO': {'pmd_category': 'basic',
            'pmd_name': 'ExtendsObject',
            'pmd_since': '5.0'},
 'PMD_ESB': {'pmd_category': 'empty',
             'pmd_name': 'EmptySynchronizedBlock',
             'pmd_since': '1.3'},
 'PMD_ESI': {'pmd_category': 'empty',
             'pmd_name': 'EmptyStaticInitializer',
             'pmd_since': '1.5'},
 'PMD_ESNIL': {'pmd_category': 'empty',
               'pmd_name': 'EmptyStatementNotInLoop',
               'pmd_since': '1.5'},
 'PMD_ESS': {'pmd_category': 'empty',
             'pmd_name': 'EmptySwitchStatements',
             'pmd_since': '1.0'},
 'PMD_ETB': {'pmd_category': 'empty',
             'pmd_name': 'EmptyTryBlock',
             'pmd_since': '0.4'},
 'PMD_EWS': {'pmd_category': 'empty',
             'pmd_name': 'EmptyWhileStmt',
             'pmd_since': '0.2'},
 'PMD_EmSB': {'pmd_category': 'empty',
              'pmd_name': 'EmptyStatementBlock',
              'pmd_since': '5.0'},
 'PMD_FDNCSF': {'pmd_category': 'finalizers',
                'pmd_name': 'FinalizeDoesNotCallSuperFinalize',
                'pmd_since': '1.5'},
 'PMD_FDSBASOC': {'pmd_category': 'design',
                  'pmd_name': 'FieldDeclarationsShouldBeAtStartOfClass',
                  'pmd_since': '5.0'},
 'PMD_FFCBS': {'pmd_category': 'design',
               'pmd_name': 'FinalFieldCouldBeStatic',
               'pmd_since': '1.1'},
 'PMD_FLMUB': {'pmd_category': 'braces',
               'pmd_name': 'ForLoopsMustUseBraces',
               'pmd_since': '0.7'},
 'PMD_FLSBWL': {'pmd_category': 'basic',
                'pmd_name': 'ForLoopShouldBeWhileLoop',
                'pmd_since': '1.02'},
 'PMD_FO': {'pmd_category': 'finalizers',
            'pmd_name': 'FinalizeOverloaded',
            'pmd_since': '1.5'},
 'PMD_FOCSF': {'pmd_category': 'finalizers',
               'pmd_name': 'FinalizeOnlyCallsSuperFinalize',
               'pmd_since': '1.5'},
 'PMD_FSBP': {'pmd_category': 'finalizers',
              'pmd_name': 'FinalizeShouldBeProtected',
              'pmd_since': '1.1'},
 'PMD_GDL': {'pmd_category': 'logging-jakarta-commons',
             'pmd_name': 'GuardDebugLogging',
             'pmd_since': '4.3'},
 'PMD_GLS': {'pmd_category': 'logging-jakarta-commons',
             'pmd_name': 'GuardLogStatement',
             'pmd_since': '5.1.0'},
 'PMD_GLSJU': {'pmd_category': 'logging-java',
               'pmd_name': 'GuardLogStatementJavaUtil',
               'pmd_since': '5.1.0'},
 'PMD_GN': {'pmd_category': 'naming',
            'pmd_name': 'GenericsNaming',
            'pmd_since': '4.2.6'},
 'PMD_IESMUB': {'pmd_category': 'braces',
                'pmd_name': 'IfElseStmtsMustUseBraces',
                'pmd_since': '0.2'},
 'PMD_IF': {'pmd_category': 'design',
            'pmd_name': 'ImmutableField',
            'pmd_since': '2.0'},
 'PMD_IFSP': {'pmd_category': 'imports',
              'pmd_name': 'ImportFromSamePackage',
              'pmd_since': '1.02'},
 'PMD_IO': {'pmd_category': 'design',
            'pmd_name': 'IdempotentOperations',
            'pmd_since': '2.0'},
 'PMD_ISB': {'pmd_category': 'strings',
             'pmd_name': 'InefficientStringBuffering',
             'pmd_since': '3.4'},
 'PMD_ISMUB': {'pmd_category': 'braces',
               'pmd_name': 'IfStmtsMustUseBraces',
               'pmd_since': '1.0'},
 'PMD_ITGC': {'pmd_category': 'design',
              'pmd_name': 'InstantiationToGetClass',
              'pmd_since': '2.0'},
 'PMD_JI': {'pmd_category': 'basic',
            'pmd_name': 'JumbledIncrementer',
            'pmd_since': '1.0'},
 'PMD_JUASIM': {'pmd_category': 'junit',
                'pmd_name': 'JUnitAssertionsShouldIncludeMessage',
                'pmd_since': '1.04'},
 'PMD_JUS': {'pmd_category': 'junit',
             'pmd_name': 'JUnitSpelling',
             'pmd_since': '1.0'},
 'PMD_JUSS': {'pmd_category': 'junit',
              'pmd_name': 'JUnitStaticSuite',
              'pmd_since': '1.0'},
 'PMD_JUTCTMA': {'pmd_category': 'junit',
                 'pmd_name': 'JUnitTestContainsTooManyAsserts',
                 'pmd_since': '5.0'},
 'PMD_JUTSIA': {'pmd_category': 'junit',
                'pmd_name': 'JUnitTestsShouldIncludeAssert',
                'pmd_since': '2.0'},
 'PMD_LHNC': {'pmd_category': 'j2ee',
              'pmd_name': 'LocalHomeNamingConvention',
              'pmd_since': '4.0'},
 'PMD_LI': {'pmd_category': 'design',
            'pmd_name': 'LogicInversion',
            'pmd_since': '5.0'},
 'PMD_LINSF': {'pmd_category': 'logging-java',
               'pmd_name': 'LoggerIsNotStaticFinal',
               'pmd_since': '2.0'},
 'PMD_LISNC': {'pmd_category': 'j2ee',
               'pmd_name': 'LocalInterfaceSessionNamingConvention',
               'pmd_since': '4.0'},
 'PMD_LoC': {'pmd_category': 'typeresolution',
             'pmd_name': 'LooseCoupling',
             'pmd_since': '3.9'},
 'PMD_MBIS': {'pmd_category': 'design',
              'pmd_name': 'MissingBreakInSwitch',
              'pmd_since': '3.0'},
 'PMD_MDBASBNC': {'pmd_category': 'j2ee',
                  'pmd_name': 'MDBAndSessionBeanNamingConvention',
                  'pmd_since': '4.0'},
 'PMD_MNC': {'pmd_category': 'basic',
             'pmd_name': 'MisplacedNullCheck',
             'pmd_since': '3.5'},
 'PMD_MRIA': {'pmd_category': 'sunsecure',
              'pmd_name': 'MethodReturnsInternalArray',
              'pmd_since': '2.2'},
 'PMD_MSMINIC': {'pmd_category': 'design',
                 'pmd_name': 'MissingStaticMethodInNonInstantiatableClass',
                 'pmd_since': '3.0'},
 'PMD_MSVUID': {'pmd_category': 'javabeans',
                'pmd_name': 'MissingSerialVersionUID',
                'pmd_since': '3.0'},
 'PMD_MTOL': {'pmd_category': 'logging-java',
              'pmd_name': 'MoreThanOneLogger',
              'pmd_since': '2.0'},
 'PMD_MWSNAEC': {'pmd_category': 'naming',
                 'pmd_name': 'MethodWithSameNameAsEnclosingClass',
                 'pmd_since': '1.5'},
 'PMD_MeNC': {'pmd_category': 'naming',
              'pmd_name': 'MethodNamingConventions',
              'pmd_since': '1.2'},
 'PMD_NCLISS': {'pmd_category': 'design',
                'pmd_name': 'NonCaseLabelInSwitchStatement',
                'pmd_since': '1.5'},
 'PMD_NP': {'pmd_category': 'naming',
            'pmd_name': 'NoPackage',
            'pmd_since': '3.3'},
 'PMD_NSI': {'pmd_category': 'design',
             'pmd_name': 'NonStaticInitializer',
             'pmd_since': '1.5'},
 'PMD_NTSS': {'pmd_category': 'design',
              'pmd_name': 'NonThreadSafeSingleton',
              'pmd_since': '3.4'},
 'PMD_OBEAH': {'pmd_category': 'basic',
               'pmd_name': 'OverrideBothEqualsAndHashcode',
               'pmd_since': '0.4'},
 'PMD_ODPL': {'pmd_category': 'controversial',
              'pmd_name': 'OneDeclarationPerLine',
              'pmd_since': '5.0'},
 'PMD_OTAC': {'pmd_category': 'design',
              'pmd_name': 'OptimizableToArrayCall',
              'pmd_since': '1.8'},
 'PMD_PC': {'pmd_category': 'naming',
            'pmd_name': 'PackageCase',
            'pmd_since': '3.3'},
 'PMD_PCI': {'pmd_category': 'clone',
             'pmd_name': 'ProperCloneImplementation',
             'pmd_since': '1.4'},
 'PMD_PL': {'pmd_category': 'logging-jakarta-commons',
            'pmd_name': 'ProperLogger',
            'pmd_since': '3.3'},
 'PMD_PLFIC': {'pmd_category': 'design',
               'pmd_name': 'PositionLiteralsFirstInComparisons',
               'pmd_since': '3.3'},
 'PMD_PLFICIC': {'pmd_category': 'design',
                 'pmd_name': 'PositionLiteralsFirstInCaseInsensitiveComparisons',
                 'pmd_since': '5.1'},
 'PMD_PST': {'pmd_category': 'design',
             'pmd_name': 'PreserveStackTrace',
             'pmd_since': '3.7'},
 'PMD_REARTN': {'pmd_category': 'design',
                'pmd_name': 'ReturnEmptyArrayRatherThanNull',
                'pmd_since': '4.2'},
 'PMD_RFFB': {'pmd_category': 'basic',
              'pmd_name': 'ReturnFromFinallyBlock',
              'pmd_since': '1.05'},
 'PMD_RFI': {'pmd_category': 'optimizations',
             'pmd_name': 'RedundantFieldInitializer',
             'pmd_since': '5.0'},
 'PMD_RINC': {'pmd_category': 'j2ee',
              'pmd_name': 'RemoteInterfaceNamingConvention',
              'pmd_since': '4.0'},
 'PMD_RSINC': {'pmd_category': 'j2ee',
               'pmd_name': 'RemoteSessionInterfaceNamingConvention',
               'pmd_since': '4.0'},
 'PMD_SBA': {'pmd_category': 'junit',
             'pmd_name': 'SimplifyBooleanAssertion',
             'pmd_since': '3.6'},
 'PMD_SBE': {'pmd_category': 'design',
             'pmd_name': 'SimplifyBooleanExpressions',
             'pmd_since': '1.05'},
 'PMD_SBIWC': {'pmd_category': 'strings',
               'pmd_name': 'StringBufferInstantiationWithChar',
               'pmd_since': '3.9'},
 'PMD_SBR': {'pmd_category': 'design',
             'pmd_name': 'SimplifyBooleanReturns',
             'pmd_since': '0.9'},
 'PMD_SC': {'pmd_category': 'design',
            'pmd_name': 'SimplifyConditional',
            'pmd_since': '3.1'},
 'PMD_SCFN': {'pmd_category': 'naming',
              'pmd_name': 'SuspiciousConstantFieldName',
              'pmd_since': '2.0'},
 'PMD_SCN': {'pmd_category': 'naming',
             'pmd_name': 'ShortClassName',
             'pmd_since': '5.0'},
 'PMD_SDFNL': {'pmd_category': 'design',
               'pmd_name': 'SimpleDateFormatNeedsLocale',
               'pmd_since': '2.0'},
 'PMD_SEJBFSBF': {'pmd_category': 'j2ee',
                  'pmd_name': 'StaticEJBFieldShouldBeFinal',
                  'pmd_since': '4.1'},
 'PMD_SEMN': {'pmd_category': 'naming',
              'pmd_name': 'SuspiciousEqualsMethodName',
              'pmd_since': '2.0'},
 'PMD_SF': {'pmd_category': 'design',
            'pmd_name': 'SingularField',
            'pmd_since': '3.1'},
 'PMD_SHMN': {'pmd_category': 'naming',
              'pmd_name': 'SuspiciousHashcodeMethodName',
              'pmd_since': '1.5'},
 'PMD_SMN': {'pmd_category': 'naming',
             'pmd_name': 'ShortMethodName',
             'pmd_since': '0.3'},
 'PMD_SOE': {'pmd_category': 'controversial',
             'pmd_name': 'SuspiciousOctalEscape',
             'pmd_since': '1.5'},
 'PMD_SP': {'pmd_category': 'logging-java',
            'pmd_name': 'SystemPrintln',
            'pmd_since': '2.1'},
 'PMD_SSSHD': {'pmd_category': 'design',
               'pmd_name': 'SwitchStmtsShouldHaveDefault',
               'pmd_since': '1.0'},
 'PMD_STS': {'pmd_category': 'strings',
             'pmd_name': 'StringToString',
             'pmd_since': '1.0'},
 'PMD_SiDTE': {'pmd_category': 'typeresolution',
               'pmd_name': 'SignatureDeclareThrowsException',
               'pmd_since': '4.0'},
 'PMD_StI': {'pmd_category': 'strings',
             'pmd_name': 'StringInstantiation',
             'pmd_since': '1.0'},
 'PMD_TCWTC': {'pmd_category': 'junit',
               'pmd_name': 'TestClassWithoutTestCases',
               'pmd_since': '3.0'},
 'PMD_TFBFASS': {'pmd_category': 'design',
                 'pmd_name': 'TooFewBranchesForASwitchStatement',
                 'pmd_since': '4.2'},
 'PMD_TMSI': {'pmd_category': 'imports',
              'pmd_name': 'TooManyStaticImports',
              'pmd_since': '4.1'},
 'PMD_UAAL': {'pmd_category': 'optimizations',
              'pmd_name': 'UseArraysAsList',
              'pmd_since': '3.5'},
 'PMD_UAEIOAT': {'pmd_category': 'junit',
                 'pmd_name': 'UseAssertEqualsInsteadOfAssertTrue',
                 'pmd_since': '3.1'},
 'PMD_UALIOV': {'pmd_category': 'optimizations',
                'pmd_name': 'UseArrayListInsteadOfVector',
                'pmd_since': '3.0'},
 'PMD_UANIOAT': {'pmd_category': 'junit',
                 'pmd_name': 'UseAssertNullInsteadOfAssertTrue',
                 'pmd_since': '3.5'},
 'PMD_UASIOAT': {'pmd_category': 'junit',
                 'pmd_name': 'UseAssertSameInsteadOfAssertTrue',
                 'pmd_since': '3.1'},
 'PMD_UATIOAE': {'pmd_category': 'junit',
                 'pmd_name': 'UseAssertTrueInsteadOfAssertEquals',
                 'pmd_since': '5.0'},
 'PMD_UBA': {'pmd_category': 'junit',
             'pmd_name': 'UnnecessaryBooleanAssertion',
             'pmd_since': '3.0'},
 'PMD_UC': {'pmd_category': 'controversial',
            'pmd_name': 'UnnecessaryConstructor',
            'pmd_since': '1.0'},
 'PMD_UCC': {'pmd_category': 'strings',
             'pmd_name': 'UnnecessaryCaseChange',
             'pmd_since': '3.3'},
 'PMD_UCEL': {'pmd_category': 'logging-jakarta-commons',
              'pmd_name': 'UseCorrectExceptionLogging',
              'pmd_since': '3.2'},
 'PMD_UCIE': {'pmd_category': 'design',
              'pmd_name': 'UseCollectionIsEmpty',
              'pmd_since': '3.9'},
 'PMD_UCT': {'pmd_category': 'unnecessary',
             'pmd_name': 'UnnecessaryConversionTemporary',
             'pmd_since': '0.1'},
 'PMD_UEC': {'pmd_category': 'design',
             'pmd_name': 'UncommentedEmptyConstructor',
             'pmd_since': '3.4'},
 'PMD_UEM': {'pmd_category': 'design',
             'pmd_name': 'UncommentedEmptyMethod',
             'pmd_since': '3.4'},
 'PMD_UETCS': {'pmd_category': 'strings',
               'pmd_name': 'UseEqualsToCompareStrings',
               'pmd_since': '4.1'},
 'PMD_UFQN': {'pmd_category': 'imports',
              'pmd_name': 'UnnecessaryFullyQualifiedName',
              'pmd_since': '5.0'},
 'PMD_UIS': {'pmd_category': 'basic',
             'pmd_name': 'UnconditionalIfStatement',
             'pmd_since': '1.5'},
 'PMD_ULBR': {'pmd_category': 'design',
              'pmd_name': 'UnnecessaryLocalBeforeReturn',
              'pmd_since': '3.3'},
 'PMD_ULV': {'pmd_category': 'unusedcode',
             'pmd_name': 'UnusedLocalVariable',
             'pmd_since': '0.1'},
 'PMD_ULWCC': {'pmd_category': 'design',
               'pmd_name': 'UseLocaleWithCaseConversions',
               'pmd_since': '2.0'},
 'PMD_UNAION': {'pmd_category': 'design',
                'pmd_name': 'UseNotifyAllInsteadOfNotify',
                'pmd_since': '3.0'},
 'PMD_UNCIE': {'pmd_category': 'unnecessary',
               'pmd_name': 'UnusedNullCheckInEquals',
               'pmd_since': '3.5'},
 'PMD_UOM': {'pmd_category': 'unnecessary',
             'pmd_name': 'UselessOverridingMethod',
             'pmd_since': '3.3'},
 'PMD_UOOI': {'pmd_category': 'unnecessary',
              'pmd_name': 'UselessOperationOnImmutable',
              'pmd_since': '3.5'},
 'PMD_UPF': {'pmd_category': 'unusedcode',
             'pmd_name': 'UnusedPrivateField',
             'pmd_since': '0.1'},
 'PMD_UPM': {'pmd_category': 'unusedcode',
             'pmd_name': 'UnusedPrivateMethod',
             'pmd_since': '0.7'},
 'PMD_USBFSA': {'pmd_category': 'optimizations',
                'pmd_name': 'UseStringBufferForStringAppends',
                'pmd_since': '3.1'},
 'PMD_USDF': {'pmd_category': 'design',
              'pmd_name': 'UnsynchronizedStaticDateFormatter',
              'pmd_since': '3.6'},
 'PMD_UV': {'pmd_category': 'design',
            'pmd_name': 'UseVarargs',
            'pmd_since': '5.0'},
 'PMD_UWOC': {'pmd_category': 'optimizations',
              'pmd_name': 'UnnecessaryWrapperObjectCreation',
              'pmd_since': '3.8'},
 'PMD_UnI': {'pmd_category': 'typeresolution',
             'pmd_name': 'UnusedImports',
             'pmd_since': '4.0'},
 'PMD_VNC': {'pmd_category': 'naming',
             'pmd_name': 'VariableNamingConventions',
             'pmd_since': '1.2'},
 'PMD_WLMUB': {'pmd_category': 'braces',
               'pmd_name': 'WhileLoopsMustUseBraces',
               'pmd_since': '0.7'}}

PMD_RULES = [{'type': 'Basic Rules', 'rule': 'Avoid Branching Statement As Last In Loop', 'abbrev': 'PMD_ABSALIL', 'severity': 'Major'}, {'type': 'Basic Rules', 'rule': 'Avoid Decimal Literals In Big Decimal Constructor', 'abbrev': 'PMD_ADLIBDC', 'severity': 'Critical'}, {'type': 'Basic Rules', 'rule': 'Avoid Multiple Unary Operators', 'abbrev': 'PMD_AMUO', 'severity': 'Major'}, {'type': 'Basic Rules', 'rule': 'Avoid Thread Group', 'abbrev': 'PMD_ATG', 'severity': 'Critical'}, {'type': 'Basic Rules', 'rule': 'Avoid Using Hard Coded IP', 'abbrev': 'PMD_AUHCIP', 'severity': 'Major'}, {'type': 'Basic Rules', 'rule': 'Avoid Using Octal Values', 'abbrev': 'PMD_AUOV', 'severity': 'Critical'}, {'type': 'Basic Rules', 'rule': 'Big Integer Instantiation', 'abbrev': 'PMD_BII', 'severity': 'Minor'}, {'type': 'Basic Rules', 'rule': 'Boolean Instantiation', 'abbrev': 'PMD_BI', 'severity': 'Minor'}, {'type': 'Basic Rules', 'rule': 'Broken Null Check', 'abbrev': 'PMD_BNC', 'severity': 'Critical'}, {'type': 'Basic Rules', 'rule': 'Check Result Set', 'abbrev': 'PMD_CRS', 'severity': 'Critical'}, {'type': 'Basic Rules', 'rule': 'Check Skip Result', 'abbrev': 'PMD_CSR', 'severity': 'Critical'}, {'type': 'Basic Rules', 'rule': 'Class Cast Exception With To Array', 'abbrev': 'PMD_CCEWTA', 'severity': 'Critical'}, {'type': 'Basic Rules', 'rule': 'Collapsible If Statements', 'abbrev': 'PMD_CIS', 'severity': 'Minor'}, {'type': 'Basic Rules', 'rule': 'Dont Call Thread Run', 'abbrev': 'PMD_DCTR', 'severity': 'Critical'}, {'type': 'Basic Rules', 'rule': 'Dont Use Float Type For Loop Indices', 'abbrev': 'PMD_DUFTFLI', 'severity': 'Critical'}, {'type': 'Basic Rules', 'rule': 'Double Checked Locking', 'abbrev': 'PMD_DCL', 'severity': 'Critical'}, {'type': 'Basic Rules', 'rule': 'Empty Catch Block', 'abbrev': 'PMD_ECB', 'severity': 'Critical'}, {'type': 'Basic Rules', 'rule': 'Empty Finally Block', 'abbrev': 'PMD_EFB', 'severity': 'Minor'}, {'type': 'Basic Rules', 'rule': 'Empty If Stmt', 'abbrev': 'PMD_EIS', 'severity': 'Major'}, {'type': 'Basic Rules', 'rule': 'Empty Statement Block', 'abbrev': 'PMD_EmSB', 'severity': 'Minor'}, {'type': 'Basic Rules', 'rule': 'Empty Statement Not In Loop', 'abbrev': 'PMD_ESNIL', 'severity': 'Minor'}, {'type': 'Basic Rules', 'rule': 'Empty Static Initializer', 'abbrev': 'PMD_ESI', 'severity': 'Minor'}, {'type': 'Basic Rules', 'rule': 'Empty Switch Statements', 'abbrev': 'PMD_ESS', 'severity': 'Major'}, {'type': 'Basic Rules', 'rule': 'Empty Synchronized Block', 'abbrev': 'PMD_ESB', 'severity': 'Major'}, {'type': 'Basic Rules', 'rule': 'Empty Try Block', 'abbrev': 'PMD_ETB', 'severity': 'Major'}, {'type': 'Basic Rules', 'rule': 'Empty While Stmt', 'abbrev': 'PMD_EWS', 'severity': 'Critical'}, {'type': 'Basic Rules', 'rule': 'Extends Object', 'abbrev': 'PMD_EO', 'severity': 'Minor'}, {'type': 'Basic Rules', 'rule': 'For Loop Should Be While Loop', 'abbrev': 'PMD_FLSBWL', 'severity': 'Minor'}, {'type': 'Basic Rules', 'rule': 'Jumbled Incrementer', 'abbrev': 'PMD_JI', 'severity': 'Critical'}, {'type': 'Basic Rules', 'rule': 'Misplaced Null Check', 'abbrev': 'PMD_MNC', 'severity': 'Critical'}, {'type': 'Basic Rules', 'rule': 'Override Both Equals And Hashcode', 'abbrev': 'PMD_OBEAH', 'severity': 'Critical'}, {'type': 'Basic Rules', 'rule': 'Return From Finally Block', 'abbrev': 'PMD_RFFB', 'severity': 'Critical'}, {'type': 'Basic Rules', 'rule': 'Unconditional If Statement', 'abbrev': 'PMD_UIS', 'severity': 'Major'}, {'type': 'Basic Rules', 'rule': 'Unnecessary Conversion Temporary', 'abbrev': 'PMD_UCT', 'severity': 'Minor'}, {'type': 'Basic Rules', 'rule': 'Unused Null Check In Equals', 'abbrev': 'PMD_UNCIE', 'severity': 'Critical'}, {'type': 'Basic Rules', 'rule': 'Useless Operation On Immutable', 'abbrev': 'PMD_UOOI', 'severity': 'Critical'}, {'type': 'Basic Rules', 'rule': 'Useless Overriding Method', 'abbrev': 'PMD_UOM', 'severity': 'Minor'}, {'type': 'Brace Rules', 'rule': 'For Loops Must Use Braces', 'abbrev': 'PMD_FLMUB', 'severity': 'Minor'}, {'type': 'Brace Rules', 'rule': 'If Else Stmts Must Use Braces', 'abbrev': 'PMD_IESMUB', 'severity': 'Minor'}, {'type': 'Brace Rules', 'rule': 'If Stmts Must Use Braces', 'abbrev': 'PMD_ISMUB', 'severity': 'Minor'}, {'type': 'Brace Rules', 'rule': 'While Loops Must Use Braces', 'abbrev': 'PMD_WLMUB', 'severity': 'Minor'}, {'type': 'Clone Implementation Rules', 'rule': 'Clone Throws Clone Not Supported Exception', 'abbrev': 'PMD_CTCNSE', 'severity': 'Major'}, {'type': 'Clone Implementation Rules', 'rule': 'Proper Clone Implementation', 'abbrev': 'PMD_PCI', 'severity': 'Critical'}, {'type': 'Controversial Rules', 'rule': 'Assignment In Operand', 'abbrev': 'PMD_AIO', 'severity': 'Minor'}, {'type': 'Controversial Rules', 'rule': 'Avoid Accessibility Alteration', 'abbrev': 'PMD_AAA', 'severity': 'Major'}, {'type': 'Controversial Rules', 'rule': 'Avoid Prefixing Method Parameters', 'abbrev': 'PMD_APMP', 'severity': 'Minor'}, {'type': 'Controversial Rules', 'rule': 'Avoid Using Native Code', 'abbrev': 'PMD_AUNC', 'severity': 'Major'}, {'type': 'Controversial Rules', 'rule': 'Default Package', 'abbrev': 'PMD_DP', 'severity': 'Minor'}, {'type': 'Controversial Rules', 'rule': 'Do Not Call Garbage Collection Explicitly', 'abbrev': 'PMD_DNCGCE', 'severity': 'Major'}, {'type': 'Controversial Rules', 'rule': 'Dont Import Sun', 'abbrev': 'PMD_DIS', 'severity': 'Major'}, {'type': 'Controversial Rules', 'rule': 'One Declaration Per Line', 'abbrev': 'PMD_ODPL', 'severity': 'Minor'}, {'type': 'Controversial Rules', 'rule': 'Suspicious Octal Escape', 'abbrev': 'PMD_SOE', 'severity': 'Major'}, {'type': 'Controversial Rules', 'rule': 'Unnecessary Constructor', 'abbrev': 'PMD_UC', 'severity': 'Minor'}, {'type': 'Design Rules', 'rule': 'Abstract Class Without Abstract Method', 'abbrev': 'PMD_ACWAM', 'severity': 'Minor'}, {'type': 'Design Rules', 'rule': 'Abstract Class Without Any Method', 'abbrev': 'PMD_AbCWAM', 'severity': 'Minor'}, {'type': 'Design Rules', 'rule': 'Assignment To Non Final Static', 'abbrev': 'PMD_ATNFS', 'severity': 'Critical'}, {'type': 'Design Rules', 'rule': 'Avoid Constants Interface', 'abbrev': 'PMD_ACI', 'severity': 'Minor'}, {'type': 'Design Rules', 'rule': 'Avoid Instanceof Checks In Catch Clause', 'abbrev': 'PMD_AICICC', 'severity': 'Major'}, {'type': 'Design Rules', 'rule': 'Avoid Protected Field In Final Class', 'abbrev': 'PMD_APFIFC', 'severity': 'Minor'}, {'type': 'Design Rules', 'rule': 'Avoid Protected Method In Final Class Not Extending', 'abbrev': 'PMD_APMIFCNE', 'severity': 'Minor'}, {'type': 'Design Rules', 'rule': 'Avoid Reassigning Parameters', 'abbrev': 'PMD_ARP', 'severity': 'Minor'}, {'type': 'Design Rules', 'rule': 'Avoid Synchronized At Method Level', 'abbrev': 'PMD_ASAML', 'severity': 'Minor'}, {'type': 'Design Rules', 'rule': 'Bad Comparison', 'abbrev': 'PMD_BC', 'severity': 'Critical'}, {'type': 'Design Rules', 'rule': 'Class With Only Private Constructors Should Be Final', 'abbrev': 'PMD_CWOPCSBF', 'severity': 'Minor'}, {'type': 'Design Rules', 'rule': 'Close Resource', 'abbrev': 'PMD_ClR', 'severity': 'Critical'}, {'type': 'Design Rules', 'rule': 'Constructor Calls Overridable Method', 'abbrev': 'PMD_CCOM', 'severity': 'Critical'}, {'type': 'Design Rules', 'rule': 'Default Label Not Last In Switch Stmt', 'abbrev': 'PMD_DLNLISS', 'severity': 'Minor'}, {'type': 'Design Rules', 'rule': 'Empty Method In Abstract Class Should Be Abstract', 'abbrev': 'PMD_EMIACSBA', 'severity': 'Major'}, {'type': 'Design Rules', 'rule': 'Equals Null', 'abbrev': 'PMD_EN', 'severity': 'Critical'}, {'type': 'Design Rules', 'rule': 'Field Declarations Should Be At Start Of Class', 'abbrev': 'PMD_FDSBASOC', 'severity': 'Minor'}, {'type': 'Design Rules', 'rule': 'Final Field Could Be Static', 'abbrev': 'PMD_FFCBS', 'severity': 'Minor'}, {'type': 'Design Rules', 'rule': 'Idempotent Operations', 'abbrev': 'PMD_IO', 'severity': 'Major'}, {'type': 'Design Rules', 'rule': 'Immutable Field', 'abbrev': 'PMD_IF', 'severity': 'Minor'}, {'type': 'Design Rules', 'rule': 'Instantiation To Get Class', 'abbrev': 'PMD_ITGC', 'severity': 'Major'}, {'type': 'Design Rules', 'rule': 'Logic Inversion', 'abbrev': 'PMD_LI', 'severity': 'Minor'}, {'type': 'Design Rules', 'rule': 'Missing Break In Switch', 'abbrev': 'PMD_MBIS', 'severity': 'Critical'}, {'type': 'Design Rules', 'rule': 'Missing Static Method In Non Instantiatable Class', 'abbrev': 'PMD_MSMINIC', 'severity': 'Minor'}, {'type': 'Design Rules', 'rule': 'Non Case Label In Switch Statement', 'abbrev': 'PMD_NCLISS', 'severity': 'Critical'}, {'type': 'Design Rules', 'rule': 'Non Static Initializer', 'abbrev': 'PMD_NSI', 'severity': 'Critical'}, {'type': 'Design Rules', 'rule': 'Non Thread Safe Singleton', 'abbrev': 'PMD_NTSS', 'severity': 'Critical'}, {'type': 'Design Rules', 'rule': 'Optimizable To Array Call', 'abbrev': 'PMD_OTAC', 'severity': 'Major'}, {'type': 'Design Rules', 'rule': 'Position Literals First In Case Insensitive Comparisons', 'abbrev': 'PMD_PLFICIC', 'severity': 'Critical'}, {'type': 'Design Rules', 'rule': 'Position Literals First In Comparisons', 'abbrev': 'PMD_PLFIC', 'severity': 'Critical'}, {'type': 'Design Rules', 'rule': 'Preserve Stack Trace', 'abbrev': 'PMD_PST', 'severity': 'Major'}, {'type': 'Design Rules', 'rule': 'Return Empty Array Rather Than Null', 'abbrev': 'PMD_REARTN', 'severity': 'Major'}, {'type': 'Design Rules', 'rule': 'Simple Date Format Needs Locale', 'abbrev': 'PMD_SDFNL', 'severity': 'Minor'}, {'type': 'Design Rules', 'rule': 'Simplify Boolean Expressions', 'abbrev': 'PMD_SBE', 'severity': 'Minor'}, {'type': 'Design Rules', 'rule': 'Simplify Boolean Returns', 'abbrev': 'PMD_SBR', 'severity': 'Minor'}, {'type': 'Design Rules', 'rule': 'Simplify Conditional', 'abbrev': 'PMD_SC', 'severity': 'Minor'}, {'type': 'Design Rules', 'rule': 'Singular Field', 'abbrev': 'PMD_SF', 'severity': 'Major'}, {'type': 'Design Rules', 'rule': 'Switch Stmts Should Have Default', 'abbrev': 'PMD_SSSHD', 'severity': 'Major'}, {'type': 'Design Rules', 'rule': 'Too Few Branches For ASwitch Statement', 'abbrev': 'PMD_TFBFASS', 'severity': 'Minor'}, {'type': 'Design Rules', 'rule': 'Uncommented Empty Constructor', 'abbrev': 'PMD_UEC', 'severity': 'Minor'}, {'type': 'Design Rules', 'rule': 'Uncommented Empty Method', 'abbrev': 'PMD_UEM', 'severity': 'Minor'}, {'type': 'Design Rules', 'rule': 'Unnecessary Local Before Return', 'abbrev': 'PMD_ULBR', 'severity': 'Minor'}, {'type': 'Design Rules', 'rule': 'Unsynchronized Static Date Formatter', 'abbrev': 'PMD_USDF', 'severity': 'Critical'}, {'type': 'Design Rules', 'rule': 'Use Collection Is Empty', 'abbrev': 'PMD_UCIE', 'severity': 'Major'}, {'type': 'Design Rules', 'rule': 'Use Locale With Case Conversions', 'abbrev': 'PMD_ULWCC', 'severity': 'Critical'}, {'type': 'Design Rules', 'rule': 'Use Notify All Instead Of Notify', 'abbrev': 'PMD_UNAION', 'severity': 'Critical'}, {'type': 'Design Rules', 'rule': 'Use Varargs', 'abbrev': 'PMD_UV', 'severity': 'Minor'}, {'type': 'Finalizer Rules', 'rule': 'Avoid Calling Finalize', 'abbrev': 'PMD_ACF', 'severity': 'Major'}, {'type': 'Finalizer Rules', 'rule': 'Empty Finalizer', 'abbrev': 'PMD_EF', 'severity': 'Minor'}, {'type': 'Finalizer Rules', 'rule': 'Finalize Does Not Call Super Finalize', 'abbrev': 'PMD_FDNCSF', 'severity': 'Critical'}, {'type': 'Finalizer Rules', 'rule': 'Finalize Only Calls Super Finalize', 'abbrev': 'PMD_FOCSF', 'severity': 'Minor'}, {'type': 'Finalizer Rules', 'rule': 'Finalize Overloaded', 'abbrev': 'PMD_FO', 'severity': 'Critical'}, {'type': 'Finalizer Rules', 'rule': 'Finalize Should Be Protected', 'abbrev': 'PMD_FSBP', 'severity': 'Critical'}, {'type': 'Import Statement Rules', 'rule': 'Dont Import Java Lang', 'abbrev': 'PMD_DIJL', 'severity': 'Minor'}, {'type': 'Import Statement Rules', 'rule': 'Duplicate Imports', 'abbrev': 'PMD_DI', 'severity': 'Minor'}, {'type': 'Import Statement Rules', 'rule': 'Import From Same Package', 'abbrev': 'PMD_IFSP', 'severity': 'Minor'}, {'type': 'Import Statement Rules', 'rule': 'Too Many Static Imports', 'abbrev': 'PMD_TMSI', 'severity': 'Major'}, {'type': 'Import Statement Rules', 'rule': 'Unnecessary Fully Qualified Name', 'abbrev': 'PMD_UFQN', 'severity': 'Minor'}, {'type': 'J2EE Rules', 'rule': 'Do Not Call System Exit', 'abbrev': 'PMD_DNCSE', 'severity': 'Critical'}, {'type': 'J2EE Rules', 'rule': 'Local Home Naming Convention', 'abbrev': 'PMD_LHNC', 'severity': 'Major'}, {'type': 'J2EE Rules', 'rule': 'Local Interface Session Naming Convention', 'abbrev': 'PMD_LISNC', 'severity': 'Major'}, {'type': 'J2EE Rules', 'rule': 'MDBAnd Session Bean Naming Convention', 'abbrev': 'PMD_MDBASBNC', 'severity': 'Major'}, {'type': 'J2EE Rules', 'rule': 'Remote Interface Naming Convention', 'abbrev': 'PMD_RINC', 'severity': 'Major'}, {'type': 'J2EE Rules', 'rule': 'Remote Session Interface Naming Convention', 'abbrev': 'PMD_RSINC', 'severity': 'Major'}, {'type': 'J2EE Rules', 'rule': 'Static EJBField Should Be Final', 'abbrev': 'PMD_SEJBFSBF', 'severity': 'Critical'}, {'type': 'JUnit Rules', 'rule': 'JUnit Assertions Should Include Message', 'abbrev': 'PMD_JUASIM', 'severity': 'Minor'}, {'type': 'JUnit Rules', 'rule': 'JUnit Spelling', 'abbrev': 'PMD_JUS', 'severity': 'Critical'}, {'type': 'JUnit Rules', 'rule': 'JUnit Static Suite', 'abbrev': 'PMD_JUSS', 'severity': 'Critical'}, {'type': 'JUnit Rules', 'rule': 'JUnit Test Contains Too Many Asserts', 'abbrev': 'PMD_JUTCTMA', 'severity': 'Minor'}, {'type': 'JUnit Rules', 'rule': 'JUnit Tests Should Include Assert', 'abbrev': 'PMD_JUTSIA', 'severity': 'Major'}, {'type': 'JUnit Rules', 'rule': 'Simplify Boolean Assertion', 'abbrev': 'PMD_SBA', 'severity': 'Minor'}, {'type': 'JUnit Rules', 'rule': 'Test Class Without Test Cases', 'abbrev': 'PMD_TCWTC', 'severity': 'Minor'}, {'type': 'JUnit Rules', 'rule': 'Unnecessary Boolean Assertion', 'abbrev': 'PMD_UBA', 'severity': 'Minor'}, {'type': 'JUnit Rules', 'rule': 'Use Assert Equals Instead Of Assert True', 'abbrev': 'PMD_UAEIOAT', 'severity': 'Major'}, {'type': 'JUnit Rules', 'rule': 'Use Assert Null Instead Of Assert True', 'abbrev': 'PMD_UANIOAT', 'severity': 'Minor'}, {'type': 'JUnit Rules', 'rule': 'Use Assert Same Instead Of Assert True', 'abbrev': 'PMD_UASIOAT', 'severity': 'Minor'}, {'type': 'JUnit Rules', 'rule': 'Use Assert True Instead Of Assert Equals', 'abbrev': 'PMD_UATIOAE', 'severity': 'Minor'}, {'type': 'Jakarta Commons Logging Rules', 'rule': 'Guard Debug Logging', 'abbrev': 'PMD_GDL', 'severity': 'Major'}, {'type': 'Jakarta Commons Logging Rules', 'rule': 'Guard Log Statement', 'abbrev': 'PMD_GLS', 'severity': 'Minor'}, {'type': 'Jakarta Commons Logging Rules', 'rule': 'Proper Logger', 'abbrev': 'PMD_PL', 'severity': 'Minor'}, {'type': 'Jakarta Commons Logging Rules', 'rule': 'Use Correct Exception Logging', 'abbrev': 'PMD_UCEL', 'severity': 'Major'}, {'type': 'Java Logging Rules', 'rule': 'Avoid Print Stack Trace', 'abbrev': 'PMD_APST', 'severity': 'Major'}, {'type': 'Java Logging Rules', 'rule': 'Guard Log Statement Java Util', 'abbrev': 'PMD_GLSJU', 'severity': 'Minor'}, {'type': 'Java Logging Rules', 'rule': 'Logger Is Not Static Final', 'abbrev': 'PMD_LINSF', 'severity': 'Minor'}, {'type': 'Java Logging Rules', 'rule': 'More Than One Logger', 'abbrev': 'PMD_MTOL', 'severity': 'Major'}, {'type': 'Java Logging Rules', 'rule': 'System Println', 'abbrev': 'PMD_SP', 'severity': 'Major'}, {'type': 'JavaBean Rules', 'rule': 'Missing Serial Version UID', 'abbrev': 'PMD_MSVUID', 'severity': 'Major'}, {'type': 'Naming Rules', 'rule': 'Avoid Dollar Signs', 'abbrev': 'PMD_ADS', 'severity': 'Minor'}, {'type': 'Naming Rules', 'rule': 'Avoid Field Name Matching Method Name', 'abbrev': 'PMD_AFNMMN', 'severity': 'Minor'}, {'type': 'Naming Rules', 'rule': 'Avoid Field Name Matching Type Name', 'abbrev': 'PMD_AFNMTN', 'severity': 'Minor'}, {'type': 'Naming Rules', 'rule': 'Boolean Get Method Name', 'abbrev': 'PMD_BGMN', 'severity': 'Minor'}, {'type': 'Naming Rules', 'rule': 'Class Naming Conventions', 'abbrev': 'PMD_CNC', 'severity': 'Minor'}, {'type': 'Naming Rules', 'rule': 'Generics Naming', 'abbrev': 'PMD_GN', 'severity': 'Minor'}, {'type': 'Naming Rules', 'rule': 'Method Naming Conventions', 'abbrev': 'PMD_MeNC', 'severity': 'Minor'}, {'type': 'Naming Rules', 'rule': 'Method With Same Name As Enclosing Class', 'abbrev': 'PMD_MWSNAEC', 'severity': 'Minor'}, {'type': 'Naming Rules', 'rule': 'No Package', 'abbrev': 'PMD_NP', 'severity': 'Minor'}, {'type': 'Naming Rules', 'rule': 'Package Case', 'abbrev': 'PMD_PC', 'severity': 'Minor'}, {'type': 'Naming Rules', 'rule': 'Short Class Name', 'abbrev': 'PMD_SCN', 'severity': 'Minor'}, {'type': 'Naming Rules', 'rule': 'Short Method Name', 'abbrev': 'PMD_SMN', 'severity': 'Minor'}, {'type': 'Naming Rules', 'rule': 'Suspicious Constant Field Name', 'abbrev': 'PMD_SCFN', 'severity': 'Minor'}, {'type': 'Naming Rules', 'rule': 'Suspicious Equals Method Name', 'abbrev': 'PMD_SEMN', 'severity': 'Critical'}, {'type': 'Naming Rules', 'rule': 'Suspicious Hashcode Method Name', 'abbrev': 'PMD_SHMN', 'severity': 'Critical'}, {'type': 'Naming Rules', 'rule': 'Variable Naming Conventions', 'abbrev': 'PMD_VNC', 'severity': 'Minor'}, {'type': 'Optimization Rules', 'rule': 'Add Empty String', 'abbrev': 'PMD_AES', 'severity': 'Minor'}, {'type': 'Optimization Rules', 'rule': 'Avoid Array Loops', 'abbrev': 'PMD_AAL', 'severity': 'Major'}, {'type': 'Optimization Rules', 'rule': 'Redundant Field Initializer', 'abbrev': 'PMD_RFI', 'severity': 'Minor'}, {'type': 'Optimization Rules', 'rule': 'Unnecessary Wrapper Object Creation', 'abbrev': 'PMD_UWOC', 'severity': 'Major'}, {'type': 'Optimization Rules', 'rule': 'Use Array List Instead Of Vector', 'abbrev': 'PMD_UALIOV', 'severity': 'Minor'}, {'type': 'Optimization Rules', 'rule': 'Use Arrays As List', 'abbrev': 'PMD_UAAL', 'severity': 'Major'}, {'type': 'Optimization Rules', 'rule': 'Use String Buffer For String Appends', 'abbrev': 'PMD_USBFSA', 'severity': 'Major'}, {'type': 'Security Code Guideline Rules', 'rule': 'Array Is Stored Directly', 'abbrev': 'PMD_AISD', 'severity': 'Major'}, {'type': 'Security Code Guideline Rules', 'rule': 'Method Returns Internal Array', 'abbrev': 'PMD_MRIA', 'severity': 'Major'}, {'type': 'Strict Exception Rules', 'rule': 'Avoid Catching Generic Exception', 'abbrev': 'PMD_ACGE', 'severity': 'Major'}, {'type': 'Strict Exception Rules', 'rule': 'Avoid Catching NPE', 'abbrev': 'PMD_ACNPE', 'severity': 'Critical'}, {'type': 'Strict Exception Rules', 'rule': 'Avoid Catching Throwable', 'abbrev': 'PMD_ACT', 'severity': 'Major'}, {'type': 'Strict Exception Rules', 'rule': 'Avoid Losing Exception Information', 'abbrev': 'PMD_ALEI', 'severity': 'Major'}, {'type': 'Strict Exception Rules', 'rule': 'Avoid Rethrowing Exception', 'abbrev': 'PMD_ARE', 'severity': 'Minor'}, {'type': 'Strict Exception Rules', 'rule': 'Avoid Throwing New Instance Of Same Exception', 'abbrev': 'PMD_ATNIOSE', 'severity': 'Minor'}, {'type': 'Strict Exception Rules', 'rule': 'Avoid Throwing Null Pointer Exception', 'abbrev': 'PMD_ATNPE', 'severity': 'Critical'}, {'type': 'Strict Exception Rules', 'rule': 'Avoid Throwing Raw Exception Types', 'abbrev': 'PMD_ATRET', 'severity': 'Major'}, {'type': 'Strict Exception Rules', 'rule': 'Do Not Extend Java Lang Error', 'abbrev': 'PMD_DNEJLE', 'severity': 'Critical'}, {'type': 'Strict Exception Rules', 'rule': 'Do Not Throw Exception In Finally', 'abbrev': 'PMD_DNTEIF', 'severity': 'Critical'}, {'type': 'Strict Exception Rules', 'rule': 'Exception As Flow Control', 'abbrev': 'PMD_EAFC', 'severity': 'Major'}, {'type': 'String and StringBuffer Rules', 'rule': 'Avoid Duplicate Literals', 'abbrev': 'PMD_ADL', 'severity': 'Major'}, {'type': 'String and StringBuffer Rules', 'rule': 'Avoid String Buffer Field', 'abbrev': 'PMD_ASBF', 'severity': 'Minor'}, {'type': 'String and StringBuffer Rules', 'rule': 'Consecutive Appends Should Reuse', 'abbrev': 'PMD_CASR', 'severity': 'Minor'}, {'type': 'String and StringBuffer Rules', 'rule': 'Consecutive Literal Appends', 'abbrev': 'PMD_CLA', 'severity': 'Minor'}, {'type': 'String and StringBuffer Rules', 'rule': 'Inefficient String Buffering', 'abbrev': 'PMD_ISB', 'severity': 'Minor'}, {'type': 'String and StringBuffer Rules', 'rule': 'String Buffer Instantiation With Char', 'abbrev': 'PMD_SBIWC', 'severity': 'Critical'}, {'type': 'String and StringBuffer Rules', 'rule': 'String Instantiation', 'abbrev': 'PMD_StI', 'severity': 'Minor'}, {'type': 'String and StringBuffer Rules', 'rule': 'String To String', 'abbrev': 'PMD_STS', 'severity': 'Minor'}, {'type': 'String and StringBuffer Rules', 'rule': 'Unnecessary Case Change', 'abbrev': 'PMD_UCC', 'severity': 'Minor'}, {'type': 'String and StringBuffer Rules', 'rule': 'Use Equals To Compare Strings', 'abbrev': 'PMD_UETCS', 'severity': 'Critical'}, {'type': 'Type Resolution Rules', 'rule': 'Clone Method Must Implement Cloneable', 'abbrev': 'PMD_ClMMIC', 'severity': 'Major'}, {'type': 'Type Resolution Rules', 'rule': 'Loose Coupling', 'abbrev': 'PMD_LoC', 'severity': 'Major'}, {'type': 'Type Resolution Rules', 'rule': 'Signature Declare Throws Exception', 'abbrev': 'PMD_SiDTE', 'severity': 'Major'}, {'type': 'Type Resolution Rules', 'rule': 'Unused Imports', 'abbrev': 'PMD_UnI', 'severity': 'Minor'}, {'type': 'Unnecessary and Unused Code Rules', 'rule': 'Unused Local Variable', 'abbrev': 'PMD_ULV', 'severity': 'Major'}, {'type': 'Unnecessary and Unused Code Rules', 'rule': 'Unused Private Field', 'abbrev': 'PMD_UPF', 'severity': 'Major'}, {'type': 'Unnecessary and Unused Code Rules', 'rule': 'Unused Private Method', 'abbrev': 'PMD_UPM', 'severity': 'Major'}]
PMD_SEVERITIES = list(set([d['severity'] for d in PMD_RULES]))
PMD_SEVERITY_MATCH = {d['abbrev']: d['severity'] for d in PMD_RULES}
PMD_GROUP_MATCH = {d['abbrev']: d['type'] for d in PMD_RULES}
PMD_SINCE = {'PMD_ABSALIL': '2012-05-01', 'PMD_ADLIBDC': '2005-11-30', 'PMD_AMUO': '2008-03-25', 'PMD_ATG': '2006-03-29', 'PMD_AUHCIP': '2007-11-17', 'PMD_AUOV': '2006-12-19', 'PMD_BII': '2006-12-19', 'PMD_BI': '2003-07-30', 'PMD_BNC': '2006-10-04', 'PMD_CRS': '2007-11-17', 'PMD_CSR': '2012-05-01', 'PMD_CCEWTA': '2005-11-30', 'PMD_CIS': '2005-05-10', 'PMD_DCTR': '2011-11-04', 'PMD_DUFTFLI': '2011-11-04', 'PMD_DCL': '2003-03-21', 'PMD_ECB': '2002-06-25', 'PMD_EFB': '2002-07-10', 'PMD_EIS': '2002-06-25', 'PMD_EmSB': '2012-05-01', 'PMD_ESNIL': '2004-02-02', 'PMD_ESI': '2004-02-02', 'PMD_ESS': '2002-11-04', 'PMD_ESB': '2003-10-23', 'PMD_ETB': '2002-07-10', 'PMD_EWS': '2002-06-27', 'PMD_EO': '2012-05-01', 'PMD_FLSBWL': '2003-01-22', 'PMD_JI': '2002-11-04', 'PMD_MNC': '2006-01-25', 'PMD_OBEAH': '2002-07-10', 'PMD_RFFB': '2003-04-17', 'PMD_UIS': '2004-02-02', 'PMD_UCT': '2002-06-25', 'PMD_UNCIE': '2006-01-25', 'PMD_UOOI': '2006-01-25', 'PMD_UOM': '2005-09-15', 'PMD_FLMUB': '2002-07-25', 'PMD_IESMUB': '2002-06-27', 'PMD_ISMUB': '2002-11-04', 'PMD_WLMUB': '2002-07-25', 'PMD_CTCNSE': '2004-07-14', 'PMD_PCI': '2004-01-07', 'PMD_AIO': '2003-02-11', 'PMD_AAA': '2007-11-17', 'PMD_APMP': '2012-05-01', 'PMD_AUNC': '2007-11-17', 'PMD_DP': '2005-11-30', 'PMD_DNCGCE': '2008-03-25', 'PMD_DIS': '2004-02-02', 'PMD_ODPL': '2012-05-01', 'PMD_SOE': '2004-02-02', 'PMD_UC': '2002-11-04', 'PMD_ACWAM': '2005-03-23', 'PMD_AbCWAM': '2008-03-25', 'PMD_ATNFS': '2005-01-31', 'PMD_ACI': '2006-01-25', 'PMD_AICICC': '2005-03-23', 'PMD_APFIFC': '2004-12-15', 'PMD_APMIFCNE': '2014-02-11', 'PMD_ARP': '2002-11-04', 'PMD_ASAML': '2005-03-23', 'PMD_BC': '2004-05-19', 'PMD_CWOPCSBF': '2007-11-17', 'PMD_ClR': '2003-10-06', 'PMD_CCOM': '2003-03-21', 'PMD_DLNLISS': '2004-02-02', 'PMD_EMIACSBA': '2007-11-17', 'PMD_EN': '2004-07-14', 'PMD_FDSBASOC': '2012-05-01', 'PMD_FFCBS': '2003-06-19', 'PMD_IO': '2004-10-19', 'PMD_IF': '2004-10-19', 'PMD_ITGC': '2004-10-19', 'PMD_LI': '2012-05-01', 'PMD_MBIS': '2005-03-23', 'PMD_MSMINIC': '2005-03-23', 'PMD_NCLISS': '2004-02-02', 'PMD_NSI': '2004-02-02', 'PMD_NTSS': '2005-11-30', 'PMD_OTAC': '2004-05-19', 'PMD_PLFICIC': '2014-02-11', 'PMD_PLFIC': '2005-09-15', 'PMD_PST': '2006-06-01', 'PMD_REARTN': '2008-03-25', 'PMD_SDFNL': '2004-10-19', 'PMD_SBE': '2003-04-17', 'PMD_SBR': '2002-08-16', 'PMD_SC': '2005-05-10', 'PMD_SF': '2005-05-10', 'PMD_SSSHD': '2002-11-04', 'PMD_TFBFASS': '2008-03-25', 'PMD_UEC': '2005-11-30', 'PMD_UEM': '2005-11-30', 'PMD_ULBR': '2005-09-15', 'PMD_USDF': '2006-03-29', 'PMD_UCIE': '2006-12-19', 'PMD_ULWCC': '2004-10-19', 'PMD_UNAION': '2005-03-23', 'PMD_UV': '2012-05-01', 'PMD_ACF': '2005-03-23', 'PMD_EF': '2004-02-02', 'PMD_FDNCSF': '2004-02-02', 'PMD_FOCSF': '2004-02-02', 'PMD_FO': '2004-02-02', 'PMD_FSBP': '2003-06-19', 'PMD_DIJL': '2002-07-15', 'PMD_DI': '2002-07-15', 'PMD_IFSP': '2003-01-22', 'PMD_TMSI': '2007-11-17', 'PMD_UFQN': '2012-05-01', 'PMD_DNCSE': '2007-11-17', 'PMD_LHNC': '2007-07-20', 'PMD_LISNC': '2007-07-20', 'PMD_MDBASBNC': '2007-07-20', 'PMD_RINC': '2007-07-20', 'PMD_RSINC': '2007-07-20', 'PMD_SEJBFSBF': '2007-11-17', 'PMD_JUASIM': '2003-03-21', 'PMD_JUS': '2002-11-04', 'PMD_JUSS': '2002-11-04', 'PMD_JUTCTMA': '2012-05-01', 'PMD_JUTSIA': '2004-10-19', 'PMD_SBA': '2006-03-29', 'PMD_TCWTC': '2005-03-23', 'PMD_UBA': '2005-03-23', 'PMD_UAEIOAT': '2005-05-10', 'PMD_UANIOAT': '2006-01-25', 'PMD_UASIOAT': '2005-05-10', 'PMD_UATIOAE': '2012-05-01', 'PMD_GDL': '2011-11-04', 'PMD_GLS': '2014-02-11', 'PMD_PL': '2005-09-15', 'PMD_UCEL': '2005-06-21', 'PMD_APST': '2005-06-21', 'PMD_GLSJU': '2014-02-11', 'PMD_LINSF': '2004-10-19', 'PMD_MTOL': '2004-10-19', 'PMD_SP': '2004-12-15', 'PMD_MSVUID': '2005-03-23', 'PMD_ADS': '2004-02-02', 'PMD_AFNMMN': '2005-03-23', 'PMD_AFNMTN': '2005-03-23', 'PMD_BGMN': '2007-07-20', 'PMD_CNC': '2003-07-30', 'PMD_GN': '2011-09-14', 'PMD_MeNC': '2003-07-30', 'PMD_MWSNAEC': '2004-02-02', 'PMD_NP': '2005-09-15', 'PMD_PC': '2005-09-15', 'PMD_SCN': '2012-05-01', 'PMD_SMN': '2002-07-03', 'PMD_SCFN': '2004-10-19', 'PMD_SEMN': '2004-10-19', 'PMD_SHMN': '2004-02-02', 'PMD_VNC': '2003-07-30', 'PMD_AES': '2007-07-20', 'PMD_AAL': '2006-01-25', 'PMD_RFI': '2012-05-01', 'PMD_UWOC': '2006-10-04', 'PMD_UALIOV': '2005-03-23', 'PMD_UAAL': '2006-01-25', 'PMD_USBFSA': '2005-05-10', 'PMD_AISD': '2005-01-31', 'PMD_MRIA': '2005-01-31', 'PMD_ACGE': '2011-09-14', 'PMD_ACNPE': '2004-05-19', 'PMD_ACT': '2003-07-30', 'PMD_ALEI': '2011-09-14', 'PMD_ARE': '2006-10-04', 'PMD_ATNIOSE': '2009-02-08', 'PMD_ATNPE': '2004-05-19', 'PMD_ATRET': '2004-05-19', 'PMD_DNEJLE': '2007-07-20', 'PMD_DNTEIF': '2008-03-25', 'PMD_EAFC': '2004-05-19', 'PMD_ADL': '2002-11-04', 'PMD_ASBF': '2008-03-25', 'PMD_CASR': '2014-02-11', 'PMD_CLA': '2006-01-25', 'PMD_ISB': '2005-11-30', 'PMD_SBIWC': '2006-12-19', 'PMD_StI': '2002-11-04', 'PMD_STS': '2002-11-04', 'PMD_UCC': '2005-09-15', 'PMD_UETCS': '2007-11-17', 'PMD_ClMMIC': '2006-12-19', 'PMD_LoC': '2006-12-19', 'PMD_SiDTE': '2007-07-20', 'PMD_UnI': '2007-07-20', 'PMD_ULV': '2002-06-25', 'PMD_UPF': '2002-06-25', 'PMD_UPM': '2002-07-25'}

# source: https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.PmdExtension.html#org.gradle.api.plugins.quality.PmdExtension:ruleSets
DEFAULT_RULES_GRADLE = ['AssignmentInOperand', 'AssignmentToNonFinalStatic', 'AvoidAccessibilityAlteration', 'AvoidAssertAsIdentifier', 'AvoidBranchingStatementAsLastInLoop', 'AvoidCallingFinalize', 'AvoidCatchingNPE', 'AvoidCatchingThrowable', 'AvoidDecimalLiteralsInBigDecimalConstructor', 'AvoidDuplicateLiterals', 'AvoidEnumAsIdentifier', 'AvoidFieldNameMatchingMethodName', 'AvoidFieldNameMatchingTypeName', 'AvoidInstanceofChecksInCatchClause', 'AvoidLiteralsInIfCondition', 'AvoidLosingExceptionInformation', 'AvoidMultipleUnaryOperators', 'AvoidUsingOctalValues', 'BadComparison', 'BeanMembersShouldSerialize', 'BrokenNullCheck', 'CallSuperFirst', 'CallSuperLast', 'CheckSkipResult', 'ClassCastExceptionWithToArray', 'CloneMethodMustBePublic', 'CloneMethodMustImplementCloneable', 'CloneMethodReturnTypeMustMatchClassName', 'CloneThrowsCloneNotSupportedException', 'CloseResource', 'CompareObjectsWithEquals', 'ConstructorCallsOverridableMethod', 'DataflowAnomalyAnalysis', 'DoNotCallGarbageCollectionExplicitly', 'DoNotCallSystemExit', 'DoNotExtendJavaLangThrowable', 'DoNotHardCodeSDCard', 'DoNotThrowExceptionInFinally', 'DontImportSun', 'DontUseFloatTypeForLoopIndices', 'EmptyCatchBlock', 'EmptyFinalizer', 'EmptyFinallyBlock', 'EmptyIfStmt', 'EmptyInitializer', 'EmptyStatementBlock', 'EmptyStatementNotInLoop', 'EmptySwitchStatements', 'EmptySynchronizedBlock', 'EmptyTryBlock', 'EmptyWhileStmt', 'EqualsNull', 'FinalizeDoesNotCallSuperFinalize', 'FinalizeOnlyCallsSuperFinalize', 'FinalizeOverloaded', 'FinalizeShouldBeProtected', 'IdempotentOperations', 'ImportFromSamePackage', 'InstantiationToGetClass', 'InvalidSlf4jMessageFormat', 'JumbledIncrementer', 'JUnitSpelling', 'JUnitStaticSuite', 'LoggerIsNotStaticFinal', 'MethodWithSameNameAsEnclosingClass', 'MisplacedNullCheck', 'MissingBreakInSwitch', 'MissingSerialVersionUID', 'MissingStaticMethodInNonInstantiatableClass', 'MoreThanOneLogger', 'NonCaseLabelInSwitchStatement', 'NonStaticInitializer', 'NullAssignment', 'OverrideBothEqualsAndHashcode', 'ProperCloneImplementation', 'ProperLogger', 'ReturnEmptyArrayRatherThanNull', 'ReturnFromFinallyBlock', 'SimpleDateFormatNeedsLocale', 'SingleMethodSingleton', 'SingletonClassReturningNewInstance', 'StaticEJBFieldShouldBeFinal', 'StringBufferInstantiationWithChar', 'SuspiciousEqualsMethodName', 'SuspiciousHashcodeMethodName', 'SuspiciousOctalEscape', 'TestClassWithoutTestCases', 'UnconditionalIfStatement', 'UnnecessaryBooleanAssertion', 'UnnecessaryCaseChange', 'UnnecessaryConversionTemporary', 'UnusedNullCheckInEquals', 'UseCorrectExceptionLogging', 'UseEqualsToCompareStrings', 'UselessOperationOnImmutable', 'UseLocaleWithCaseConversions', 'UseProperClassLoader']

# source: https://maven.apache.org/plugins/maven-pmd-plugin/examples/usingRuleSets.html
DEFAULT_RULES_MAVEN = ['AvoidUsingHardCodedIP', 'CheckResultSet', 'UnusedImports', 'UnusedFormalParameter', 'UnusedLocalVariable', 'UnusedPrivateField', 'UnusedPrivateMethod', 'DontImportJavaLang', 'DuplicateImports', 'ExtendsObject', 'ForLoopShouldBeWhileLoop', 'TooManyStaticImports', 'UnnecessaryFullyQualifiedName', 'UnnecessaryModifier', 'UnnecessaryReturn', 'UselessParentheses', 'UselessQualifiedThis', 'CollapsibleIfStatements', 'SimplifiedTernary', 'UselessOverridingMethod', 'AvoidBranchingStatementAsLastInLoop', 'AvoidDecimalLiteralsInBigDecimalConstructor', 'AvoidMultipleUnaryOperators', 'AvoidUsingOctalValues', 'BrokenNullCheck', 'CheckSkipResult', 'ClassCastExceptionWithToArray', 'DontUseFloatTypeForLoopIndices', 'EmptyCatchBlock', 'EmptyFinallyBlock', 'EmptyIfStmt', 'EmptyInitializer', 'EmptyStatementBlock', 'EmptyStatementNotInLoop', 'EmptySwitchStatements', 'EmptySynchronizedBlock', 'EmptyTryBlock', 'EmptyWhileStmt', 'ImportFromSamePackage', 'JumbledIncrementer', 'MisplacedNullCheck', 'OverrideBothEqualsAndHashcode', 'ReturnFromFinallyBlock', 'UnconditionalIfStatement', 'UnnecessaryConversionTemporary', 'UnusedNullCheckInEquals', 'UselessOperationOnImmutable', 'AvoidThreadGroup', 'DontCallThreadRun', 'DoubleCheckedLocking', 'BigIntegerInstantiation', 'BooleanInstantiation']

# cleaned by removing rules SourceMeter does not have, also use SourceMeter name
DEFAULT_RULES_GRADLE_CLEANED = ['PMD_AIO', 'PMD_ATNFS', 'PMD_AAA', 'PMD_ABSALIL', 'PMD_ACF', 'PMD_ACNPE', 'PMD_ACT', 'PMD_ADLIBDC', 'PMD_ADL', 'PMD_AFNMMN', 'PMD_AFNMTN', 'PMD_AICICC', 'PMD_ALEI', 'PMD_AMUO', 'PMD_AUOV', 'PMD_BC', 'PMD_BNC', 'PMD_CSR', 'PMD_CCEWTA', 'PMD_ClMMIC', 'PMD_CTCNSE', 'PMD_ClR', 'PMD_CCOM', 'PMD_DNCGCE', 'PMD_DNCSE', 'PMD_DNTEIF', 'PMD_DIS', 'PMD_DUFTFLI', 'PMD_ECB', 'PMD_EF', 'PMD_EFB', 'PMD_EIS', 'PMD_EmSB', 'PMD_ESNIL', 'PMD_ESS', 'PMD_ESB', 'PMD_ETB', 'PMD_EWS', 'PMD_EN', 'PMD_FDNCSF', 'PMD_FOCSF', 'PMD_FO', 'PMD_FSBP', 'PMD_IO', 'PMD_IFSP', 'PMD_ITGC', 'PMD_JI', 'PMD_JUS', 'PMD_JUSS', 'PMD_LINSF', 'PMD_MWSNAEC', 'PMD_MNC', 'PMD_MBIS', 'PMD_MSVUID', 'PMD_MSMINIC', 'PMD_MTOL', 'PMD_NCLISS', 'PMD_NSI', 'PMD_OBEAH', 'PMD_PCI', 'PMD_PL', 'PMD_REARTN', 'PMD_RFFB', 'PMD_SDFNL', 'PMD_SEJBFSBF', 'PMD_SBIWC', 'PMD_SEMN', 'PMD_SHMN', 'PMD_SOE', 'PMD_TCWTC', 'PMD_UIS', 'PMD_UBA', 'PMD_UCC', 'PMD_UCT', 'PMD_UNCIE', 'PMD_UCEL', 'PMD_UETCS', 'PMD_UOOI', 'PMD_ULWCC']
DEFAULT_RULES_MAVEN_CLEANED = ['PMD_AUHCIP', 'PMD_CRS', 'PMD_UnI', 'PMD_ULV', 'PMD_UPF', 'PMD_UPM', 'PMD_DIJL', 'PMD_DI', 'PMD_EO', 'PMD_FLSBWL', 'PMD_TMSI', 'PMD_UFQN', 'PMD_CIS', 'PMD_UOM', 'PMD_ABSALIL', 'PMD_ADLIBDC', 'PMD_AMUO', 'PMD_AUOV', 'PMD_BNC', 'PMD_CSR', 'PMD_CCEWTA', 'PMD_DUFTFLI', 'PMD_ECB', 'PMD_EFB', 'PMD_EIS', 'PMD_EmSB', 'PMD_ESNIL', 'PMD_ESS', 'PMD_ESB', 'PMD_ETB', 'PMD_EWS', 'PMD_IFSP', 'PMD_JI', 'PMD_MNC', 'PMD_OBEAH', 'PMD_RFFB', 'PMD_UIS', 'PMD_UCT', 'PMD_UNCIE', 'PMD_UOOI', 'PMD_ATG', 'PMD_DCTR', 'PMD_DCL', 'PMD_BII', 'PMD_BI']

# mapping of sourcemeter name to pmd category
PMD_CATEGORY = {'PMD_ABSALIL': 'basic', 'PMD_ADLIBDC': 'basic', 'PMD_AMUO': 'basic', 'PMD_ATG': 'basic', 'PMD_AUHCIP': 'basic', 'PMD_AUOV': 'basic', 'PMD_BII': 'basic', 'PMD_BI': 'basic', 'PMD_BNC': 'basic', 'PMD_CRS': 'basic', 'PMD_CSR': 'basic', 'PMD_CCEWTA': 'basic', 'PMD_CIS': 'basic', 'PMD_DCTR': 'basic', 'PMD_DUFTFLI': 'basic', 'PMD_DCL': 'basic', 'PMD_ECB': 'empty', 'PMD_EFB': 'empty', 'PMD_EIS': 'empty', 'PMD_EmSB': 'empty', 'PMD_ESNIL': 'empty', 'PMD_ESI': 'empty', 'PMD_ESS': 'empty', 'PMD_ESB': 'empty', 'PMD_ETB': 'empty', 'PMD_EWS': 'empty', 'PMD_EO': 'basic', 'PMD_FLSBWL': 'basic', 'PMD_JI': 'basic', 'PMD_MNC': 'basic', 'PMD_OBEAH': 'basic', 'PMD_RFFB': 'basic', 'PMD_UIS': 'basic', 'PMD_UCT': 'unnecessary', 'PMD_UNCIE': 'unnecessary', 'PMD_UOOI': 'unnecessary', 'PMD_UOM': 'unnecessary', 'PMD_FLMUB': 'braces', 'PMD_IESMUB': 'braces', 'PMD_ISMUB': 'braces', 'PMD_WLMUB': 'braces', 'PMD_CTCNSE': 'clone', 'PMD_PCI': 'clone', 'PMD_AIO': 'controversial', 'PMD_AAA': 'controversial', 'PMD_APMP': 'controversial', 'PMD_AUNC': 'controversial', 'PMD_DP': 'controversial', 'PMD_DNCGCE': 'controversial', 'PMD_DIS': 'controversial', 'PMD_ODPL': 'controversial', 'PMD_SOE': 'controversial', 'PMD_UC': 'controversial', 'PMD_ACWAM': 'design', 'PMD_AbCWAM': 'design', 'PMD_ATNFS': 'design', 'PMD_ACI': 'design', 'PMD_AICICC': 'design', 'PMD_APFIFC': 'design', 'PMD_APMIFCNE': 'design', 'PMD_ARP': 'design', 'PMD_ASAML': 'design', 'PMD_BC': 'design', 'PMD_CWOPCSBF': 'design', 'PMD_ClR': 'design', 'PMD_CCOM': 'design', 'PMD_DLNLISS': 'design', 'PMD_EMIACSBA': 'design', 'PMD_EN': 'design', 'PMD_FDSBASOC': 'design', 'PMD_FFCBS': 'design', 'PMD_IO': 'design', 'PMD_IF': 'design', 'PMD_ITGC': 'design', 'PMD_LI': 'design', 'PMD_MBIS': 'design', 'PMD_MSMINIC': 'design', 'PMD_NCLISS': 'design', 'PMD_NSI': 'design', 'PMD_NTSS': 'design', 'PMD_OTAC': 'design', 'PMD_PLFICIC': 'design', 'PMD_PLFIC': 'design', 'PMD_PST': 'design', 'PMD_REARTN': 'design', 'PMD_SDFNL': 'design', 'PMD_SBE': 'design', 'PMD_SBR': 'design', 'PMD_SC': 'design', 'PMD_SF': 'design', 'PMD_SSSHD': 'design', 'PMD_TFBFASS': 'design', 'PMD_UEC': 'design', 'PMD_UEM': 'design', 'PMD_ULBR': 'design', 'PMD_USDF': 'design', 'PMD_UCIE': 'design', 'PMD_ULWCC': 'design', 'PMD_UNAION': 'design', 'PMD_UV': 'design', 'PMD_ACF': 'finalizers', 'PMD_EF': 'finalizers', 'PMD_FDNCSF': 'finalizers', 'PMD_FOCSF': 'finalizers', 'PMD_FO': 'finalizers', 'PMD_FSBP': 'finalizers', 'PMD_DIJL': 'imports', 'PMD_DI': 'imports', 'PMD_IFSP': 'imports', 'PMD_TMSI': 'imports', 'PMD_UFQN': 'imports', 'PMD_DNCSE': 'j2ee', 'PMD_LHNC': 'j2ee', 'PMD_LISNC': 'j2ee', 'PMD_MDBASBNC': 'j2ee', 'PMD_RINC': 'j2ee', 'PMD_RSINC': 'j2ee', 'PMD_SEJBFSBF': 'j2ee', 'PMD_JUASIM': 'junit', 'PMD_JUS': 'junit', 'PMD_JUSS': 'junit', 'PMD_JUTCTMA': 'junit', 'PMD_JUTSIA': 'junit', 'PMD_SBA': 'junit', 'PMD_TCWTC': 'junit', 'PMD_UBA': 'junit', 'PMD_UAEIOAT': 'junit', 'PMD_UANIOAT': 'junit', 'PMD_UASIOAT': 'junit', 'PMD_UATIOAE': 'junit', 'PMD_GDL': 'logging-jakarta-commons', 'PMD_GLS': 'logging-jakarta-commons', 'PMD_PL': 'logging-jakarta-commons', 'PMD_UCEL': 'logging-jakarta-commons', 'PMD_APST': 'logging-java', 'PMD_GLSJU': 'logging-java', 'PMD_LINSF': 'logging-java', 'PMD_MTOL': 'logging-java', 'PMD_SP': 'logging-java', 'PMD_MSVUID': 'javabeans', 'PMD_ADS': 'naming', 'PMD_AFNMMN': 'naming', 'PMD_AFNMTN': 'naming', 'PMD_BGMN': 'naming', 'PMD_CNC': 'naming', 'PMD_GN': 'naming', 'PMD_MeNC': 'naming', 'PMD_MWSNAEC': 'naming', 'PMD_NP': 'naming', 'PMD_PC': 'naming', 'PMD_SCN': 'naming', 'PMD_SMN': 'naming', 'PMD_SCFN': 'naming', 'PMD_SEMN': 'naming', 'PMD_SHMN': 'naming', 'PMD_VNC': 'naming', 'PMD_AES': 'optimizations', 'PMD_AAL': 'optimizations', 'PMD_RFI': 'optimizations', 'PMD_UWOC': 'optimizations', 'PMD_UALIOV': 'optimizations', 'PMD_UAAL': 'optimizations', 'PMD_USBFSA': 'optimizations', 'PMD_AISD': 'sunsecure', 'PMD_MRIA': 'sunsecure', 'PMD_ACGE': 'strictexception', 'PMD_ACNPE': 'strictexception', 'PMD_ACT': 'strictexception', 'PMD_ALEI': 'strictexception', 'PMD_ARE': 'strictexception', 'PMD_ATNIOSE': 'strictexception', 'PMD_ATNPE': 'strictexception', 'PMD_ATRET': 'strictexception', 'PMD_DNEJLE': 'strictexception', 'PMD_DNTEIF': 'strictexception', 'PMD_EAFC': 'strictexception', 'PMD_ADL': 'strings', 'PMD_ASBF': 'strings', 'PMD_CASR': 'strings', 'PMD_CLA': 'strings', 'PMD_ISB': 'strings', 'PMD_SBIWC': 'strings', 'PMD_StI': 'strings', 'PMD_STS': 'strings', 'PMD_UCC': 'strings', 'PMD_UETCS': 'strings', 'PMD_ClMMIC': 'typeresolution', 'PMD_LoC': 'typeresolution', 'PMD_SiDTE': 'typeresolution', 'PMD_UnI': 'typeresolution', 'PMD_ULV': 'unusedcode', 'PMD_UPF': 'unusedcode', 'PMD_UPM': 'unusedcode'}

# mapping of pmd name to sourcemeter name
PMD_NAME_TO_SM = {v['pmd_name']: k for k, v in PMD_RULES_SINCE.items()}